= CAM experimental
:page-origin: https://wiki.freecad.org/CAM_experimental/de
:page-origin-revision: ec21aac21d 2026-07-18
:page-imported: true

== Beschreibung

Der Arbeitsbereich CAM enthält eine Reihe versteckter Befehle. Diese sind standardmäßig ausgeblendet, da sie sich noch in der Testphase befinden. Ein Befehl kann aus einem der folgenden Gründe als experimentell betrachtet werden:

* Er ist unvollständig.
* Er ist fehlerhaft.
* Er ist instabil.
* Er erzeugt keine korrekten, stabilen und sicheren Pfade.
* Es handelt sich nicht um einen Standardbefehl, der im traditionellen CAM-Arbeitsablauf regelmäßig verwendet wird.
* Er ist ausgereift, wurde jedoch noch nicht in die Standard-Werkzeugliste aufgenommen.
* ... andere Gründe.

== Experimentelle Befehle aktivieren

Um auf die versteckten experimentellen Befehle des Arbeitsbereichs CAM zugreifen zu können, muss der Benutzer diese aktivieren.

=== Die Befehle xref:operations/surface.adoc[CAM Oberfläche] und xref:operations/waterline.adoc[CAM Wasserlinie] aktivieren

. Den https://wiki.freecad.org/Preferences_Editor[Voreinstellungseditor] über menu:Bearbeiten[Einstellungen] öffnen.
. Gehe zur Seite menu:CAM[Erweitert].
. Das Kontrollkästchen menu:OCL-abhängige Funktionen aktivieren[] auswählen.
. FreeCAD neu starten.

=== Andere experimentelle Befehle aktivieren

. Den https://wiki.freecad.org/Std_DlgParameter[Parameterdialog] über menu:Werkzeuge[Parameter bearbeiten] öffnen.
. Im Editor lautet der Pfad dann menu:BaseApp[Preferences > Mod > CAM].
. Mit der rechten Maustaste in den Bereich der Parameterliste klicken und im Kontextmenü menu:Neu[Neues boolesches Element] auswählen.
. Name des neuen Parameters: `EnableExperimentalFeatures` (Groß-/Kleinschreibung beachten).
. Auf `True` setzen.
. Die Einstellungen speichern.
. FreeCAD neu starten.

== Zusätzliche Informationen

Weitere Informationen zu den spezifischen experimentellen Befehlen findet man unter https://wiki.freecad.org/Special:WhatLinksHere/CAM_experimental[Wiki-Seiten&#44; die auf diese Seite verweisen].
