= OpenCamLib
:page-origin: https://wiki.freecad.org/OpenCamLib/de
:page-imported: true

== Beschreibung

OpenCamLib (OCL) ist eine Open-Source-Bibliothek, die Algorithmen für die computergestützte Fertigung (CAM) bereitstellt. FreeCAD verwendet OCL in den experimentellen image:Path_Surface.svg[width=24] xref:operations/surface.adoc[CAM Oberfläche]-Pfadoperationen und anderen experimentellen Funktionen.

GitHub: https://github.com/aewallin/opencamlib

Homepage: http://www.anderswallin.net/CAM/

== Installieren

=== Windows

*Hinweis:* Ab FreeCAD Version 0.19 sollte OCL in allen Windows-Distributionspaketen enthalten sein.

To install OCL on Windows, follow these instructions.

. Obtain the Python version of OpenCamLib (OCL).
* Build from https://github.com/aewallin/opencamlib[source] using the Python version used by your FreeCAD version. Peter Lama's https://github.com/peterlama/opencamlib[fork of the same] source has project files for a MSVC build.
* Download the Python 2.7 x86/x64 https://github.com/sgrogan/opencamlib/releases[binary] by sgrogan on GitHub.
* Download the Python 3.6 x64 https://github.com/sgrogan/opencamlib/releases[binary] by sgrogan on GitHub.
. Navigate to your OCL build _or_ binary folder
. Copy the *ocl.pyd* library file
. Proceed with one of the following four(4) options:
* Navigate to your *FreeCAD++\++lib* folder, and paste the *ocl.pyd* file there. (''This is the preferred option.'')
* Navigate to your *FreeCAD++\++bin* folder, and paste the *ocl.pyd* file there.
* Navigate to your *FreeCAD++\++Mod* folder. Create a new folder, *OCL*. Enter the *OCL* folder and paste the *ocl.pyd* file.
* Navigate to your *%USERPROFILE%++\++AppData++\++Roaming++\++FreeCAD* folder. Create a new folder, *Mod*. Enter the *Mod* folder. Create a new *OCL* folder. Enter the *OCL* folder and paste the *ocl.pyd* file. (''This is the least preferred option.'')
. Restart FreeCAD
. Verify proper installation
.. Click *View* → *Panels* → *Python console*.
.. Type "*import ocl*" into the Python console and press the *enter* key.
.. If no error appears, you have correctly installed OCL
* If you receive an error:
** Check the placement and name of the *ocl.pyd* file as instructed above
** Verify the correct architecture type of the OCL library you installed - x86 or x64
** Verify the Python version used to build the OCL library is the same as that of your FreeCAD software - 2.7 or 3.6 currently

=== Linux

Das Repository befindet sich https://github.com/aewallin/opencamlib[hier] und enthält grundlegende Installationsanweisungen.

Vor Beginn der Installation oder während des Installationsvorgangs wird man wahrscheinlich feststellen, dass man einige zusätzliche Pakete installieren muss:

==== Ubuntu/Debian

Zum Beispiel: 
[source,bash]
----
sudo apt install cmake
sudo apt install libboost-program-options-dev
# Optional, for documentation:
sudo apt-get install doxygen
sudo apt-get install texlive-full
----

Hinweis: "libboost-program-options-dev" kann durch "libboost-all-dev" ersetzt werden.

Wenn man Probleme hat, überprüft man sorgfältig alle Fehlermeldungen, die man während der cmake- und make-Phasen erhält, da man möglicherweise zusätzliche Pakete installieren muss.

==== Archlinux

. Man installiert OpenCamLib aus dem https://aur.archlinux.org/packages/opencamlib-git[AUR-Paket].
. Dann führt man den folgenden Codeausschnitt in der https://wiki.freecad.org/Python_Console[Python-Konsole] von FreeCAD aus.

[source,bash]
----
import sys
sys.path.append('/usr/opencamlib/')
import ocl
----

==== Python 3

Die Version von cmake mit `cmake --version` identifizieren, die man installiert hat.

Für cmake ++>++= 3.12 fügt man diese Markierungen (flags) hinzu:

[source,bash]
----
cmake -DBUILD_PY_LIB=ON -DUSE_PY_3=ON -DCMAKE_BUILD_TYPE=Release ../src -Wno-dev
----

Für cmake ++<++ 3.12 (wie in Ubuntu 18.04, das 3.10 hat) muss man zunächst `src/pythonlib/pythonlib.cmake` bearbeiten und diesen Patch anwenden:

`Index: opencamlib-2019.07/src/pythonlib/pythonlib.cmake` +
`===================================================================` +
`--- opencamlib-2019.07.orig/src/pythonlib/pythonlib.cmake` +
`{plus}{plus}{plus} opencamlib-2019.07/src/pythonlib/pythonlib.cmake` +
`@@ -48,13 {plus}48,13 @@ if($++{++CMAKE++_++VERSION} VERSION++_++LESS "3.12.0` +
`     message("Python not found")` +
`   endif()` +
`   execute++_++process(` +
`-    COMMAND $++{++PYTHON++_++EXECUTABLE} -c "from distutils.sysconfig import get++_++python++_++lib; print get++_++python++_++lib(0,0,++\++"/usr/local++\++")"` +
`{plus}    COMMAND $++{++PYTHON++_++EXECUTABLE} -c "import site; print(site.getsitepackages()++[++-1++]++)"` +
`     OUTPUT++_++VARIABLE PYTHON++_++SITE++_++PACKAGES` +
`     OUTPUT++_++STRIP++_++TRAILING++_++WHITESPACE` +
`   ) ++#++ on Ubuntu 11.10 this outputs: /usr/local/lib/python2.7/dist-packages` +
` ` +
`   execute++_++process(` +
`-    COMMAND $++{++PYTHON++_++EXECUTABLE} -c "from distutils.sysconfig import get++_++python++_++lib; print get++_++python++_++lib(plat++_++specific=1,standard++_++lib=0,prefix=++\++"/usr/local++\++")"` +
`{plus}    COMMAND $++{++PYTHON++_++EXECUTABLE} -c "import site; print(site.getsitepackages()++[++-1++]++)"` +
`     OUTPUT++_++VARIABLE PYTHON++_++ARCH++_++PACKAGES` +
`     OUTPUT++_++STRIP++_++TRAILING++_++WHITESPACE` +
`   )`

Damit Python 3 korrekt erkannt wird, muss man der cmake-Zeile zwei weitere Markierungen (flags) hinzufügen:

[source,bash]
----
cmake -DBUILD_PY_LIB=ON -DUSE_PY_3=ON -DPYTHON_EXECUTABLE="$(which python3)" -DPYTHON_VERSION_SUFFIX=3 -DCMAKE_BUILD_TYPE=Release ../src -Wno-dev
----

Siehe das FreeCAD-Forum unter https://forum.freecad.org/viewtopic.php?p=316970#p316988[Re: How to activate openCamLib after compiling it], und einige nachfolgende Beiträge.

=== Mac

[source,bash]
----
git clone https://github.com/aewallin/opencamlib
cd opencamlib
mkdir build
cd build
cmake -DBUILD_PY_LIB=ON -DUSE_PY_3=ON -DCMAKE_BUILD_TYPE=Release .. -Wno-dev
make -j4
make install
----

Um den Build zu testen, gibt man Folgendes in die https://wiki.freecad.org/Python_Console[Python-Konsole] ein:

[source,python]
----
import area
import ocl
dir(ocl)
----

Der Rückgabewert sollte lauten:

[source,python]
----
['AdaptivePathDropCutter', 'AdaptivePathDropCutter_base', 'AdaptiveWaterline', 'AdaptiveWaterline_base', 'Arc', 'ArcSpanType', 'BallConeCutter', 'BallCutter', 'BatchDropCutter', 'BatchDropCutter_base', 'BatchPushCutter', 'BatchPushCutter_base', 'Bbox', 'BullConeCutter', 'BullCutter', 'CCPoint', 'CCType', 'CLPoint', 'CompBallCutter', 'CompCylCutter', 'ConeConeCutter', 'ConeCutter', 'CutterLocationSurface', 'CylConeCutter', 'CylCutter', 'Ellipse', 'EllipsePosition', 'Fiber', 'Fiber_base', 'Interval', 'Line', 'LineCLFilter', 'LineCLFilter_base', 'LineSpanType', 'MillingCutter', 'Path', 'PathDropCutter', 'PathDropCutter_base', 'Path_base', 'Point', 'STLReader', 'STLSurf', 'STLSurf_base', 'SpanType', 'Triangle', 'Triangle_base', 'Waterline', 'Waterline_base', 'WeaveVertexType', 'ZigZag', 'ZigZag_base', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'eps', 'epsD', 'epsF', 'version']
----

Im Falle eines Fehlers lautet der Rückgabewert:

[source,python]
----
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
----

Für cmake ist die Option Release sehr wichtig, da es bei Verwendung des Debug-Bereichs zu Konflikten mit ocl kommt und eine der beiden Bibliotheken nicht geladen wird (je nachdem, welche zuerst geladen wurde).

== Weitere Hilfe

Falls man auf Schwierigkeiten stößt, findet man zusätzliche Hilfe in diesen Forenbeiträgen:

* https://forum.freecad.org/viewtopic.php?t=19205[Windows]
* https://forum.freecad.org/viewtopic.php?t=18017[Linux]

== Danksagungen

Dank an http://www.anderswallin.net/about/[Dr. Anders Wallin] für die Bereitstellung von OCL für die Öffentlichkeit.
