= CAM Adaptive
:page-origin: https://wiki.freecad.org/CAM_Adaptive
:page-origin-revision: c2d2c2d286 2025-12-08
:page-command: CAM_Adaptive
:page-icon: CAM_Adaptive.svg
:page-menu: CAM → Adaptive
:page-workbench: CAM
:page-imported: true

[.fcinfobox]
--
[.fcTitle]
image:CAM_Adaptive.svg[CAM Adaptive,32] *CAM Adaptive*

Menu location:: menu:CAM[Adaptive]
Workbenches:: xref:index.adoc[CAM]
Default shortcut:: _None_
Introduced in version:: -
See also:: _None_
--

== Description

The image:CAM_Adaptive.svg[width=24] xref:operations/adaptive.adoc[CAM Adaptive] command creates clearing and profiling paths. The operation varies cutter engagement so that the material removal never exceeds a maximum value.

== Usage

Usage instructions for the xref:operations/adaptive.adoc[Adaptive] operation are presented here.

=== Basic Operation

. Press the image:CAM_Adaptive.svg[width=16] xref:operations/adaptive.adoc[Adaptive] icon, or select the kbd:[CAM] → image:CAM_Adaptive.svg[width=24] xref:operations/adaptive.adoc[Adaptive] from the top menu.
. Select the tool controller for the Operation from the Tool controller dialogue pop up window, if prompted.
. Adjust the operation depths as needed in the Depths tab: Start Depth, Finish Depth, Step Down.
. Make adjustments in Heights tab if needed.
. Configure settings in the Operations tab:
.. (*See the <<properties,Properties>> → Adaptive section below.*)
.. Set the Step Over value as a percentage of the diameter of the Tool.
. If you wish to preview the result before accepting the settings, click btn:[Apply]
. Click btn:[OK] button to confirm and generate paths.

=== Preliminary Notes About Adaptive Clearing

* Depending on the size and complexity of the area for the operation, is might be better to not recompute the operation after every property change; rather, consider:
** deactivate the operation with the image:CAM_OpActiveToggle.svg[width=16] xref:inspect/op-active-toggle.adoc[Active] toggle tool, make your changes to the operation's properties, then click the image:CAM_OpActiveToggle.svg[width=16] xref:inspect/op-active-toggle.adoc[Active] icon again to re-activate the operation - which triggers a recompute internally.
* The image:CAM_Adaptive.svg[width=16] xref:operations/adaptive.adoc[Adaptive] operation might contain a few bugs yet to be clearly identified. Please report bugs and issues in the https://forum.freecad.org/viewforum.php?f=15[FreeCAD Path/CAM Forum].
* All tool shapes may not be respected with this operation. Check the FreeCAD forum for further details.
* Should you choose to run the path simulator in the CAM Workbench, it only uses the standard end mill to simulate paths. Therefore, you will not see tool-shape-specific material removal. Material removal is shown using the end mill shape.

== Properties

*_Note_*: The names of some Properties in this list differ a little from the same settings used in the Task Window Editor.

.Adaptive
* *Force Inside-Out*: Force plunging into material inside and clearing towards the edges
* *Helix Angle*: Helix ramp entry angle (degrees)
* *Helix Cone Angle*: Angle (degrees) of conical helix
* *Helix Diameter Limit*: Limit helix entry diameter, if limit larger than tool diameter or 0, tool diameter is used
* *Keep Tool Down Ratio*: Max length of keep tool down path compared to direct distance between points
* *Lift Distance*: Lift distance for rapid moves
* *Operation Type*: Type of adaptive operation: Clearing or Profiling
* *Side*: Side of selected faces that tool should cut: Inside or Outside
* *Step Over*: Percent of cutter diameter to step over on each pass
* *Stock to Leave*: How much stock to leave (i.e. for a separate finishing operation)
* *Tolerance*: Influences accuracy and performance
* *Use Helix Arcs*: Use Arcs (G2) for helix ramp

.Base
Note: It is suggested that you do not edit the Placement property of path operations. Rather, move or rotate the CAM Job model as needed.

* *Placement*: Overall placement++[++position and rotation++]++ of the object - with respect to the origin (or origin of parent object container)
** *Angle*: Angle in degrees applied to rotation of the object around Axis property value
** *Axis*: Axis (one or multiple) around which to rotate the object, set in sub-properties: X, Y, Z
*** *X*: X-axis value
*** *Y*: Y-axis value
*** *Z*: Z axis value
** *Position*: Position of the object, set in sub-properties: X, Y, Z - with respect to the origin (or origin of parent object container)
*** *X*: X-distance value
*** *Y*: Y-distance value
*** *Z*: Z-distance value
* *Label*: User-provided name of the object (UTF-8)

.Depth
* *Clearance Height*: The height needed to clear clamps and obstructions
* *Final Depth*: Final Depth of Tool- lowest value in Z
* *Finish Depth*: Maximum material removed on final pass.
* *Safe Height*: The above which Rapid motions are allowed.
* *Start Depth*: Starting Depth of Tool- first cut depth in Z
* *Step Down*: Incremental Step Down of Tool

.Path
* *Active*: Make False, to prevent operation from generating code
* *Comment*: An optional comment for this Operation
* *User Label*: User assigned label
* *Tool Controller*: Defines the Tool controller used in the Operation

== Tasks Window Editor Layout

_Descriptions for these settings are provided in the Properties list above._

This section is simply a layout map of the settings in the window editor for the Operation.

=== Base Geometry

* *Add*: Adds selected element(s) which should be the base(s) for the path(s).
* *Delete*: Delete the selected item(s) in the Base Geometry list.
* *Clear*: Clear all items in the Base Geometry list.

=== Depths

* *Start Depth*
* *Final Depth*
* *Finish Depth*
* *Step Down*

=== Heights

* *Safe Height*
* *Clearance Height*

=== Operation

* *Tool Controller*
* *Cut Region* (Side)
* *Operation Type*
* *Step Over Percent*
* *Accuracy vs Performance* (Tolerance)
* *Helix Ramp Angle*
* *Helix Cone Angle*
* *Helix Max Diameter* (Helix Diameter Limit)
* *Lift Distance*
* *Keep Tool Down Ratio*
* *Stock to Leave*
* *Force Clearing Inside-Out*
* *Stop*

== Known Issues

In case CAM Adaptive creates some unwanted paths, try with a *Stock to Leave* set to `0.001 mm` or more. You can reduce the diameter of the tool by double that amount to keep the paths exact.

A proposed bugfix is available (but no one is working on integrating it):

https://github.com/FreeCAD/FreeCAD/pull/5276

== Resources

* Author's GitHub page for the original project: https://github.com/kreso-t/FreeCAD_Mod_Adaptive_Path[kreso-t/FreeCAD++_++Mod++_++Adaptive++_++Path]
* Active topic in FreeCAD forums for Path Adaptive operation: https://forum.freecad.org/viewtopic.php?f=15&t=30127[Adaptive Path/CAM Operation]
