= CAM Comment
:page-origin: https://wiki.freecad.org/CAM_Comment
:page-origin-revision: f1f4cec1fe 2025-11-05
:page-command: CAM_Comment
:page-icon: CAM_Comment.svg
:page-menu: CAM → Supplemental Commands → Comment
:page-workbench: CAM
:page-imported: true

[.fcinfobox]
--
[.fcTitle]
image:CAM_Comment.svg[CAM Comment,32] *CAM Comment*

Menu location:: menu:CAM[Supplemental Commands > Comment]
Workbenches:: xref:index.adoc[CAM]
Default shortcut:: _None_
Introduced in version:: -
See also:: _None_
--

== Description

The image:CAM_Comment.svg[width=24] xref:operations/comment.adoc[CAM Comment] command inserts a comment. When exporting a project to G-code, the comments will be inserted in the G-code program, and can be read by people reading the file. Some machine controllers will also display comments on their display screens.

== Usage

. Press the image:CAM_Comment.svg[width=16] xref:operations/comment.adoc[Comment] button or use the kbd:[P] then kbd:[C] keyboard shortcut.
. Write your comment in the *Comment* property

== Properties

* *Comment*: The text of your comment

== Scripting

See also: https://wiki.freecad.org/FreeCAD_Scripting_Basics[FreeCAD Scripting Basics].

Example:

[source,python]
----
#Place code example here.
----
