= CAM Surface
:page-origin: https://wiki.freecad.org/CAM_Surface
:page-origin-revision: a8351b0dcf 2026-05-22
:page-command: CAM_Surface
:page-icon: CAM_Surface.svg
:page-menu: CAM → 3D Surface
:page-workbench: CAM
:page-since: 0.19
:page-imported: true

WARNING: This is an unfinished experimental feature. See xref:reference/experimental.adoc[Enable Experimental Features].

NOTE: This page is incomplete; it was marked as unfinished on the wiki.

[.fcinfobox]
--
[.fcTitle]
image:CAM_Surface.svg[CAM Surface,32] *CAM Surface*

Menu location:: menu:CAM[3D Surface]
Workbenches:: xref:index.adoc[CAM]
Default shortcut:: _None_
Introduced in version:: 0.19
See also:: _None_
--

== Description

The image:CAM_Surface.svg[width=24] xref:operations/surface.adoc[CAM Surface] command creates a new 3D Surface operation which is capable of generating G-code paths for the entire top surface of a 3D model (or is able to work with selected faces) and allows for faces to be avoided. This operation offers multiple cut patterns: Line, Zigzag, Circular, Circular Zigzag, Offset, and Spiral (similar to an adaptive pattern). As of version 0.19, this operation offers many customizations to allow for greater productivity.

The 3D Surface command is also capable of generating basic rotational 3D surfacing paths. The rotational capabilities are limited to the entire model, and do not allow for specific faces or regions to be isolated. The rotational paths are also limited to line cut patterns.

The command interfaces to OCL.pyd, a 3rd party Open Source module titled xref:reference/opencamlib.adoc[OpenCamLib], that generates tool paths from a 3D model. OpenCamLib is not integrated directly into FreeCAD.

*Note:* In order to use the 3D Surface operation you must:

. Properly install xref:reference/opencamlib.adoc[OpenCamLib].
. Enable xref:reference/experimental.adoc[Experimental Features] for the CAM Workbench.
. Check menu:Edit[Preferences > CAM > Advanced > Enable OCL dependent features].

== Usage

Usage instructions for multiple variations of the xref:operations/surface.adoc[3D Surface] operation are presented here.

=== Basic Operation

. Press the image:CAM_Surface.svg[width=24] xref:operations/surface.adoc[3D Surface] icon, or select menu:CAM[3D Surface] from the dropdown menu.
. Select the tool controller for the Operation from the Tool controller dialogue pop up window, if presented.
. In the Base Geometry tab, select any specific faces you wish to focus on and/or avoid for the operation.
. Adjust the operation depths as needed in the Depths tab: Start Depth, Finish Depth, Step Down.
. Make adjustments in Heights tab if needed.
. Configure settings in the Operations tab as needed:
* Choose your Coolant Mode.
* Choose the BoundBox: Stock or BaseBoundBox
* Set the Scan Type for the operation: Planar or Rotational
* Select the Layer Mode for the operation: Single-pass or Multi-pass
.. Single-pass is for a finishing pass
.. Multi-pass could be used for clearing in combination with the use of Depth Offset to leave a thin surface layer for a finish pass
* Add additional BoundBox Extra Offset to X and Y as desired (_Rotational scans only_)
* Set the Drop Cutter Direction: X or Y. This is the linear direction the cutter(spindle) will travel. (_Rotational scans only_)
* Add a Depth Offset value if you wish to leave a specified thickness of material on the surface, for say a final finish pass
* Set the Sample Interval used for the OCL scan.
* Set the Step Over value as a percentage of the diameter of the Tool.
* Check the Use Start Point box if you wish to provide a start point for the operation in the properties view of the data tab for the operation.
* Boundary Enforcement is enabled by default. This forces the cutter to remain inside the boundaries of the feature geometry for the operation, like a pocketing operation. Disable to allow the cutter to extend to the outside of the feature geometry. The Boundary Adjustment property supersedes this property.
* Optimize Linear Paths is enabled by default. Disabling will yield a longer gcode result and likely increase cut time.
. If you wish to preview the result before accepting the settings, click btn:[Apply]
. Click btn:[OK] button to confirm and generate paths.

To achieve different, or more complex, effects, adjust additional operation properties within the Data tab of the https://wiki.freecad.org/Property_View[Properties View] for the operation.

==== Rotational Scans (4th-axis)

. Initiate a <<basic-operation,Basic Operation>> as described above and set the *Scan Type* to *Rotational*.
. *Note:* Face selection is unavailable for Rotational scans, so changes to Base Geometry are ignored.
. Locate the Data tab and Properties View for the new xref:operations/surface.adoc[3D Surface] operation. A *Rotation* section should be available with additional properties to adjust, listed below. +
It is recommended that you set the desired rotation properties all at once before recomputing. This is done by clicking the ENTER key immediately after changing a property setting. This process will allow you to change and save multiple properties before recomputing the operation.
. Adjust the following settings as needed:
* Set *Cutter Tilt* to the offset index(angle) ++[++0-90++]++. (Used for ball mill cutters)
* Change *Drop Cutter Dir* to the axis of travel for the cutter (spindle).
* Change *Drop Cutter Extra Offset* to extend the BoundBox in the X and Y directions.
* Set *Rotation Axis* to the desired axis.
* Adjust *Start Index* to start index(angle) ++[++0-360++]++.
* Adjust *Stop Index* to stop index(angle) ++[++0-360++]++.
. Click the image:View-refresh.svg[width=16] https://wiki.freecad.org/Std_Refresh[Refresh] icon in the tool bar.
. Wait for the results...

===== Notes About Rotational Scans

* *Rotational* scans require much more time and processing than *Planar* scans. Factors affecting processing time include: Sample Interval, Step Over, tool diameter, and model size. Again, rotational scans can take a long time. Some might take 3, 5 or 10 minutes or longer.
* For time purposes, it is better that you not recompute a rotational scan after every property change; rather, consider one of the following:
** use the ' _change all settings with ENTER key_ ' technique mentioned in Step 2 above, then image:View-refresh.svg[width=16] https://wiki.freecad.org/Std_Refresh[Refresh] the operation.
** deactivate the operation with the image:CAM_OpActiveToggle.svg[width=16] xref:inspect/op-active-toggle.adoc[Active] toggle tool, make your changes to the operation's properties, then click the image:CAM_OpActiveToggle.svg[width=16] xref:inspect/op-active-toggle.adoc[Active] icon again to re-activate the operation - which triggers a recompute internally.
* The image:CAM_Surface.svg[width=16] xref:operations/surface.adoc[3D Surface] command is still considered an _experimental feature_ as of 2019-06-25. As such, it may contain a few bugs yet to be clearly identified. Please report bugs and issues in the https://forum.freecad.org/viewforum.php?f=15[FreeCAD CAM Forum].
* The built in image:CAM_Simulator.svg[width=16] xref:inspect/simulator-legacy.adoc[CAM Simulator] does NOT support 4th-axis simulation. You will need to use a third party simulator to inspect or verify paths visually. See the <<resources,Resources>> section below for suggestions.
* You will likely see red rotational lines around your model in the viewport. This is normal in FreeCAD for the time being.

===== Notes About Scans of complex models

Excessively long processing times (longer than 10 minutes) can occur when processing large complex models. In addition to the factors already mentioned the following steps could help identify potential causes and solutions.

*_Low Memory_* +
Check how much memory is available while the scan is running using a tool such as the Windows *Task Manager, Memory tab*. If more than 90% of memory is consistently being used then a small *Linear Deflection* parameter could be generating a mesh that is too large for the available memory. +
To confirm this:

. Create a new image:CAM_Surface.svg[width=24] xref:operations/surface.adoc[3D Surface] command.
. Switch to the Model tab and increase the *Linear Deflection* value. For example change from 2.5um to 20um.
. Switch back to the Tasks tab to complete setting up the operation.
. Click btn:[OK] button to confirm and generate paths. +

To make this value the default for all new image:CAM_Surface.svg[width=24] xref:operations/surface.adoc[3D Surface] commands, change the *GeometryTolerance* parameter. +
menu:Tools[Edit Parameters > Preferences > Mod > CAM > GeometryTolerance]. +
Note as of version 0.19 the *Linear Deflection* default = GeometryTolerance / 4

*_Invalid Geometry_* +
If a model contains invalid geometry the scanning time can increase significantly. A model can be checked using the https://wiki.freecad.org/Part_CheckGeometry[Part CheckGeometry] function in image:Workbench_Part.svg[width=24] https://wiki.freecad.org/Part_Workbench[Part Workbench]. +
To run the tool:

. Switch to the image:Workbench_Part.svg[width=24]**Part Workbench** and select the model to check
. Click on the image:Part_CheckGeometry.svg[width=16] https://wiki.freecad.org/Part_CheckGeometry[Part CheckGeometry] button available in the Part workbench toolbar OR use the menu:Part[Check geometry] entry from the top menu.
. Click the *Run Check* button and review the results.

If the results includes items like _BOPAlgo SelfIntersect_ then the geometry is invalid and should be corrected by adjusting the model. +
(Hint: Boolean operations and Loft commands can sometimes introduce _Self Intersections_) +

==== Available Tool (Cutter) Shapes

This 3D Surface op currently uses xref:reference/opencamlib.adoc[OpenCamLib] to extract paths from the part base. As such, a tool setting translation is required between the FreeCAD tool controller and OCL in order to complete the scan with your chosen tool(cutter) shape.

These tool shapes are respected and available for this 3D Surface operation:

* End mill
* Ball end mill
* Bull nose end mill
* Chamfer bit
* Engraver

Should you choose to run the path simulator in the CAM Workbench, it only uses the standard end mill to simulate paths. Therefore, you will not see tool-shape-specific material removal. Material removal is shown using the end mill shape.

NOTE: As of May 2019, only the End Mill has any type of testing to determine accuracy of the FreeCAD-to-OCL tool settings translation. Please post any feedback for non-end-mill usage to the https://forum.freecad.org/viewforum.php?f=15[CAM] section in the FreeCAD forums.

== Properties: Version 0.19

*_Note_*: Not all of these Properties are available in the Task Window Editor. Some are only accessible in the Data tab of the https://wiki.freecad.org/Property_View[Properties View] panel for this Operation.

.Base
Note: It is suggested that you do not edit the Placement property of path operations. Rather, move or rotate the CAM Job model as needed.

* *Placement*: Overall placement ++[++position and rotation++]++ of the object - with respect to the origin (or origin of parent object container)
** *Angle*: Angle in degrees applied to rotation of the object around Axis property value
** *Axis*: Axis (one or multiple) around which to rotate the object, set in sub-properties: X, Y, Z
*** *X*: X-axis value
*** *Y*: Y-axis value
*** *Z*: Z-axis value
** *Position*: Position of the object, set in sub-properties: X, Y, Z - with respect to the origin (or origin of parent object container)
*** *X*: X-distance value
*** *Y*: Y-distance value
*** *Z*: Z-distance value
* *Label*: User-provided name of the object (UTF-8)

.Clearing Options
* *Bound Box*: Should the operation be limited by the stock object or by the bounding box of the base object
* *Cut Mode*: The direction that the toolpath should go around the part: Climb (ClockWise/CW) or Conventional (CounterClockWise/CCW)
* *Cut Pattern*: Clearing pattern to use
* *Cut Pattern Reversed*: Reverse the cut order of the stepover paths. For circular cut patterns, begin at the outside and work toward the center
* *Depth Offset*: Z-axis offset from the surface of the object
* *Layer Mode*: The completion mode for the operation: single or multi-pass
* *Pattern Center At*: Choose location of the center point for starting the cut pattern
* *Pattern Center Custom*: Set the start point for the cut pattern
* *Profile Edges*: Profile the edges of the selection. There are the following options (images can be seen in this forum post: https://forum.freecad.org/viewtopic.php?p=676452#p676452):
** *None*: Don't create a profile
** *Only*: Create only a profile and no inner paths
** *First*: Start with the profile and then do the rest
** *Last*: Start with the rest and then do the profile
* *Sample Interval*: The Sample Interval. Small values cause long wait times
* *Step Over*: Step over percentage of the drop cutter path

.Depth
* *Clearance Height*: The height needed to clear clamps and obstructions
* *Final Depth*: Final Depth of Tool- lowest value in Z
* *Safe Height*: The above which Rapid motions are allowed.
* *Start Depth*: Starting Depth of Tool- first cut depth in Z
* *Step Down*: Incremental Step Down of Tool

.Mesh Conversion
* *Angular Deflection*: Smaller values yield a finer, more accurate mesh. Smaller values increase processing time a lot
* *Linear Deflection*: Smaller values yield a finer, more accurate mesh. Smaller values do not increase processing time much but can increase memory comsumption

.Optimization
* *Circular Use G2 G3*: Convert co-planar arcs to G2/G3 gcode commands for 'Circular' and 'CircularZigZag' cut patterns
* *Gap Sizes*: Feedback: three smallest gaps identified in the path geometry
* *Gap Threshold*: Collinear and co-radial artifact gaps that are smaller than this threshold are closed in the path
* *Optimize Linear Paths*: Enable optimization of linear paths (co-linear points). Removes unnecessary co-linear points from G-Code output
* *Optimize Step Over Transitions*: Enable separate optimization of transitions between, and breaks within, each step over path

.Path
* *Active*: Make False, to prevent operation from generating code
* *Base*: The base geometry for this operation
* *Comment*: An optional comment for this Operation
* *Coolant Mode*: Coolant mode for this operation
* *Cycle Time*: Operations Cycle Time Estimation
* *Tool Controller*: Defines the Tool controller used in the Operation
* *User Label*: User assigned label

.Rotation
* *Cutter Tilt*: Set the cutter (spindle) tilt angle.
* *Drop Cutter Dir*: The direction along which dropcutter lines are created
* *Drop Cutter Extra Offset*: Additional offset to the selected bounding box - use sub-properties to set values
** *X*: X-distance value
** *Y*: Y-distance value
** *Z*: Z-distance value
* *Rotation Axis*: Set the axis for model rotation.
* *Start Index*: Start index(angle) for rotation
* *Stop Index*: Stop index(angle) for rotation

.Selected Geometry Settings
* *Avoid Last X Faces*: Avoid cutting the last 'N' faces in the Base Geometry list of selected faces
* *Avoid Last X Internal Features*: Do not cut internal features on avoided faces
* *Boundary Adjustment*: Positive values push the cutter toward, or beyond, the boundary. Negative values retract the cutter away from the boundary
* *Boundary Enforcement*: If true, the cutter will remain inside the boundaries of the model or selected face(s)
* *Handle Multiple Features*: Choose how to process multiple Base Geometry features
* *Internal Features Adjustment*: Positive values push the cutter toward, or into, the feature. Negative values retract the cutter away from the feature
* *Internal Features Cut*: Cut internal feature areas within a larger selected face

.Start Point
* *Start Point*: The custom start point for the path of this operation, set in sub-properties: X, Y, Z
** *X*: X-axis value
** *Y*: Y-axis value
** *Z*: Z axis value
* *Use Start Point*: Make True, if specifying a Start Point

.Surface
* *Scan Type*: Planar: Flat, 3D surface scan. Rotational: 4th-axis rotational scan.

.Waste
* *Ignore Waste*: Ignore areas that proceed below specified depth.
* *Ignore Waste Depth*: Depth used to identify waste areas to ignore.
* *Release From Waste*: Cut through waste to depth at model edge, releasing the model.

== Tasks Window Editor Layout

_Descriptions for the settings are provided in the Properties list above._

This section is simply a layout map of the settings in the window editor for the Operation.

=== Base Location

* *Base Geometry import selection*: Use this list to select Base Geometry to be imported from the selected, existing operation
* *Import*: Imports the selected operation's Base Geometry into the current operations Base Geometry list
* *Base Geometry list for current operation*: List of Base Geometry for current operation, if any selected
* *Add*: Adds selected element(s) which should be the base(s) for the path(s)
* *Remove*: Remove the selected item(s) in the Base Location list
* *Clear*: Clear all items in the Base Location list

=== Depth

* *Start Depth*
* *Final Depth*
* *Step Down*

=== Height

* *Safe Height*
* *Clearance Height*

=== Operation

* *Tool Controller*
* *Coolant Mode*

* *BoundBox*
* *Scan Type*
* *Layer Mode*
* *BoundBox extra offset X*
* *BoundBox extra offset Y*
* *Drop Cutter Direction*
* *Depth Offset*
* *Step Over*
* *Sample Interval*
* *Optimize Output Enabled*

* *Use Start Point*
* *Boundary Enforcement*
* *Optimize Linear Paths*

== Resources

* G-code(path) simulator: https://ncviewer.com/[NCViewer]
* G-code(path) simulator: https://www.camotics.org/[CAMotics]
