= CAM DressupPathBoundary
:page-origin: https://wiki.freecad.org/CAM_DressupPathBoundary
:page-origin-revision: 3cd8e7218c 2025-11-05
:page-command: CAM_DressupPathBoundary
:page-icon: CAM_DressupPathBoundary.svg
:page-menu: CAM → Path Dressup → Boundary
:page-workbench: CAM
:page-see-also: CAM DressupTag, CAM DressupRampEntry
:page-imported: true

[.fcinfobox]
--
[.fcTitle]
image:CAM_DressupPathBoundary.svg[CAM DressupPathBoundary,32] *CAM DressupPathBoundary*

Menu location:: menu:CAM[Path Dressup > Boundary]
Workbenches:: xref:index.adoc[CAM]
Default shortcut:: _None_
Introduced in version:: -
See also:: xref:dressups/tag.adoc[CAM DressupTag], xref:dressups/ramp-entry.adoc[CAM DressupRampEntry]
--

== Description

The image:CAM_DressupPathBoundary.svg[width=24] xref:dressups/path-boundary.adoc[CAM DressupPathBoundary] command allows restricting the extent of a path to a smaller part of the object. For example, restricting a profile path to just one face or part of the model.

== Usage

. Select a path such as contour, profile or pocket operation.
. Select the menu:CAM[Path Dressup > Boundary] option from the menu.

== Options

* *Create Box*
* *Create Cylinder*
* *Extend Model's Boundary Box*: A very convenient way to limit a path is to select this option and use negative values.
* *Use Existing Solid*

== Limitations

* The _Create Box_ option only sets the dimensions of the box, not its origin. To alter its origin it is necessary to adjust its _Placement_ in the https://wiki.freecad.org/Tree_View[Tree View].
