= CAM experimental
:page-origin: https://wiki.freecad.org/CAM_experimental/fr
:page-origin-revision: 91c9753015 2026-07-08
:page-imported: true

== Description

L'atelier CAM contient un ensemble de commandes cachées. Elles sont cachées par défaut car elles sont expérimentales. Une commande peut être considérée comme expérimentale pour l'une des raisons suivantes :

* Elle est incomplète.
* Elle présente des bogues.
* Elle est instable.
* Elle ne produit pas de chemins corrects, stables, sûrs.
* Il ne s'agit pas d'une commande standard, régulièrement utilisée dans le déroulement traditionnel de la FAO.
* Elle est mature mais n'a pas encore été déplacée vers la liste d'outils standard.
* ... d'autres raisons.

== Activer les commandes expérimentales

Pour accéder aux commandes expérimentales masquées dans de l'atelier CAM, l'utilisateur doit les activer.

=== Activer les commandes xref:operations/surface.adoc[Surfaçage 3D] et xref:operations/waterline.adoc[Lignes de niveau]

. Ouvrez le https://wiki.freecad.org/Preferences_Editor[réglage des préférences] via menu:Édition[Préférences].
. Accédez à la page menu:CAM[Avancé].
. Cochez la case menu:Activer les fonctions dépendantes d'openCAMlib[].
. Redémarrez FreeCAD.

=== Activer d'autres commandes expérimentales

. Ouvrez l'https://wiki.freecad.org/Std_DlgParameter[éditeur de paramètres] via menu:Outils[Éditer les paramètres].
. Une fois dans l'éditeur, le chemin d'accès est menu:BaseApp[Preferences > Mod > CAM].
. Cliquez avec le bouton droit de la souris dans la zone de la liste des paramètres et sélectionnez menu:Nouveau[Nouvel élément booléen] dans le menu contextuel.
. Nommez le nouveau paramètre : `EnableExperimentalFeatures` (sensible à la casse).
. Définissez-le sur : `True`.
. Enregistrez les paramètres.
. Redémarrez FreeCAD.

== Informations supplémentaires

En savoir plus sur les commandes expérimentales spécifiques sur les https://wiki.freecad.org/Special:WhatLinksHere/CAM_experimental[pages du wiki qui renvoient à celle-ci].
