= CAM Entrée/sortie
:page-origin: https://wiki.freecad.org/CAM_DressupLeadInOut/fr
:page-origin-revision: 7825d130ee 2026-06-08
:page-command: CAM_DressupLeadInOut
:page-icon: CAM_DressupLeadInOut.svg
:page-menu: CAM → Finition du parcours → Entrée/sortie
:page-workbench: CAM
:page-see-also: CAM Dégagement d'angles, CAM Attaches, CAM Rampe d'entrée, CAM Lame rotative
:page-imported: true

[.fcinfobox]
--
[.fcTitle]
image:CAM_DressupLeadInOut.svg[CAM Entrée/sortie,32] *CAM Entrée/sortie*

Menu location:: menu:CAM[Finition du parcours > Entrée/sortie]
Workbenches:: xref:index.adoc[CAM]
Default shortcut:: _None_
Introduced in version:: -
See also:: xref:dressups/dogbone.adoc[CAM Dégagement d'angles], xref:dressups/tag.adoc[CAM Attaches], xref:dressups/ramp-entry.adoc[CAM Rampe d'entrée], xref:dressups/drag-knife.adoc[CAM Lame rotative]
--

== Description

La commande image:CAM_DressupLeadInOut.svg[width=24] xref:dressups/lead-in-out.adoc[Entrée/sortie] améliore un parcours existant en ajoutant des mouvements d'entrée et de sortie au début et à la fin du parcours de l'outil.

== Utilisation

. Sélectionnez un objet de chemin existant.
. Il existe plusieurs façons de lancer la commande :
* Cliquez sur le bouton image:CAM_DressupLeadInOut.svg[width=16] xref:dressups/lead-in-out.adoc[Entrée/Sortie].
* Sélectionnez l'option menu:CAM[Finition du parcours > Entrée/sortie] du menu.
. Réglez les paramètres d'entrée et de sortie dans le panneau des tâches.
. Confirmez la modification.

== Options

* *Entrée* : permet de contrôler le déplacement en entrée ajouté avant le parcours de coupe principal.
* *Sortie* : Permet de contrôler le déplacement en sortie ajouté après le parcours de coupe principal.
* *Vitesse d'avance* : les déplacements d'entrée et de sortie utilisent des vitesses d'avance définies pour ces déplacements dans le contrôleur d'outils. Par défaut, celles-ci suivent la vitesse d'avance horizontale. [.since]#introduced in 26.3#

== Limitations

* Ce mode de personnalisation modifie le début et la fin d'un parcours existant.
* Le résultat exact dépend du chemin sélectionné et des paramètres d'entrée et de sortie choisis.
* image:CAM_DressupRampEntry.svg[width=16] xref:dressups/ramp-entry.adoc[CAM Rampe d'entrée] peut également être appliqué à un parcours qui comporte déjà une fonction d'entrée/sortie. [.since]#introduced in 26.3#

== Script

[source,python]
----
Add python code here
----
