= CAM ToolShape
:page-origin: https://wiki.freecad.org/CAM_ToolShape/fr
:page-origin-revision: ebe6d349e4 2026-05-21
:page-imported: true

== Description

Les formes d'outils sont un élément essentiel du système des xref:tools/index.adoc[CAM Outils]. Les formes d'outils sont les modèles à partir desquels les outils coupants sont créés. Elles représentent la forme physique spécifique d'un outil. Une forme d'outil ne décrit pas complètement l'outil, pour cela, des paramètres supplémentaires sont nécessaires, qui seront ajoutés lorsqu'un outil réel sera paramétré à partir du modèle.

Initialement, les formes d'outils sont juste des documents FreeCAD avec un seul corps créé à partir de l'image:Workbench_PartDesign.svg[width=24] https://wiki.freecad.org/PartDesign_Workbench[atelier PartDesign].

La création de nouvelles formes d'outils est un sujet avancé. Les formes d'outils les plus couramment utilisés existent déjà et sont fournis avec l'installation de FreeCAD à l'adresse suivante :

* Sous Linux, il s'agit généralement de `/usr/lib64/FreeCAD/Mod/CAM/Tools/Shape`.
* Sous Windows, il s'agit généralement de `C:\Program Files\FreeCAD\Mod\CAM\Tools\Shape`.
* Sous macOS, il s'agit généralement de `/Applications/FreeCAD.app/Contents/Resources/Mod/CAM/Tools/Shape`.

Ce sont :

::
  `ballend.fcstd`
  +
  `bullnose.fcstd`
  +
  `chamfer.fcstd`
  +
  `drill.fcstd`
  +
  `endmill.fcstd`
  +
  `probe.fcstd`
  +
  `slittingsaw.fcstd`
  +
  `thread-mill.fcstd`
  +
  `v-bit.fcstd`

Elles se trouvent dans le sous-répertoire `/Mod/CAM/Tools/Shape/` où FreeCAD a été installé.

== Utilisation

. Créez un nouveau document FreeCAD.
. Ouvrez l'image:Workbench_PartDesign.svg[width=16] https://wiki.freecad.org/PartDesign_Workbench[atelier PartDesign].
. Créez un https://wiki.freecad.org/PartDesign_Body[corps] et donnez au corps une étiquette que vous voulez voir apparaître dans la sélection des outils.
. Créez une image:PartDesign_NewSketch.svg[width=16] https://wiki.freecad.org/PartDesign_NewSketch[esquisse] sur le plan XZ et dessinez la moitié du profil de l'outil.
. Contraignez le centre le plus bas de l'outil sur l'origine `(0,0)`. Ce sera le centre de l'axe sur lequel le G-code fera tourner l'outil.
* Remarque : n'ajoutez pas de contraintes dimensionnelles pour le moment.
. Fermez l'esquisse.
. Faites une image:PartDesign_Revolution.svg[width=16] https://wiki.freecad.org/PartDesign_Revolution[révolution] de l'esquisse autour de l'axe vertical de l'esquisse.
. Ouvrez l'image:Workbench_CAM.svg[width=16] xref:index.adoc[atelier CAM].
. Sélectionnez l'esquisse dans l'https://wiki.freecad.org/Tree_View[arborescence]. Cela garantit que le conteneur d'attributs d'outil coupant (PropertyBag) créé à l'étape suivante sera imbriqué dans le corps.
. Sélectionnez l'option menu:CAM[Utilitaires > Conteneur d'attibuts d'outil coupant] du menu.
. Un conteneur d'attributs d'outil coupant nommé `Attributs` est créé. Ce conteneur d'attributs d'outil coupant sera utilisé pour contrôler les dimensions dans l'esquisse.
. Double-cliquez sur le conteneur d'attributs d'outil coupant dans l'https://wiki.freecad.org/Tree_View[arborescence].
. Le panneau de tâches menu:Conteneur d'attributs d'outil coupant[] s'ouvre.
. Cliquez sur le bouton btn:[Ajouter...].
. La fenêtre de dialogue menu:Créer une propriété[] s'ouvre.
. Créez une propriété nommée `Diameter`. Cette propriété est obligatoire pour les outils coupants. Les noms de propriété sont sensibles à la casse et ne peuvent pas contenir d'espaces.
. Sélectionnez `Shape` dans la liste déroulante menu:Groupe[].
. Sélectionnez le menu:Type[] approprié.
. Vous pouvez spécifier un menu:ToolTip[].
. Cliquez sur le bouton btn:[OK].
. Dans le panneau de tâches menu:Conteneur d'attributs d'outil coupant[], entrez une valeur pour la propriété _Diameter_.
. De même, ajoutez toutes les autres propriétés requises.
. Cliquez sur le bouton btn:[OK] dans le panneau de tâches menu:Conteneur d'attributs d'outil coupant[] lorsque vous avez terminé.
. Double-cliquez sur l'esquisse dans l'https://wiki.freecad.org/Tree_View[arborescence].
. Ajoutez des contraintes dimensionnelles et appliquez les propriétés du Conteneur d'attibuts d'outil coupant créé. Par exemple, pour appliquer la propriété *Diameter* :
.. Double-cliquez sur une dimension.
.. Cliquez sur l'icône image:Bound-expression.svg[width=16].
.. Saisissez `<<Attributs>>.Diameter` dans l'menu:Éditeur de formule[].
.. Cliquez deux fois sur le bouton btn:[OK].
. Répétez cette opération jusqu'à ce que l'esquisse soit entièrement contrainte.
. Enregistrez le fichier `FCStd` là où FreeCAD s'attend à trouver les fichiers des outils coupants. Voir <<description,Description>> ci-dessus.

* Note 1. Si l'accès au dossier vous est refusé sous Windows, démarrez FreeCAD en mode ADMINISTRATEUR.
* Note 2. Le corps de l'outil coupant doit être le premier objet dans l'https://wiki.freecad.org/Tree_View[arborescence]. Ces instructions garantissent que c'est le cas.

== Images miniatures des outils

Les outils coupants auront une petite icône de l'outil dans l'https://wiki.freecad.org/Tree_View[arborescence] si le fichier est enregistré avec les vignettes actives.

Remarques importantes :

* Avant d'enregistrer le document, assurez-vous que vous avez sélectionné Save Thumbnail et désélectionné Add program logo dans les préférences de FreeCAD.
* Assurez-vous également de passer en vue de face et d'adapter le contenu à l'écran.
* Ce que vous voyez lorsque vous enregistrez le document sera la représentation visuelle du modèle.
