= CAM ToolBit Library
:page-origin: https://wiki.freecad.org/CAM_ToolBit_Library/de
:page-imported: true

NOTE: This page is incomplete; it was marked as unfinished on the wiki.

== Beschreibung

Innerhalb des xref:tools/index.adoc[CAM Werkzeug]-Systems sind Werkzeugbits in Bibliotheken organisiert. Eine Bibliothek ist einfach eine Liste von Werkzeugbits und kann vom Benutzer für jeden beliebigen Zweck verwendet werden. Eine Werkzeugbibliothek ist dennoch eine gute Darstellung für eine physische Gruppierung von Werkzeugen, wie beispielsweise in einem automatischen Werkzeugwechsler. Oder Werkzeuge können nach ihrem Verwendungszweck gruppiert werden, beispielsweise alle Werkzeuge zum Schneiden von Kunststoff.

Eine Werkzeugbibliothek ist eine (JSON-)Datei, die eine Zuordnung der Werkzeug-ID zum Pfad der Werkzeugbit-Datei enthält. Folglich kann jedes Werkzeugbit in mehreren Bibliotheken enthalten sein.

Da jedes WErkzeug in einer eigenen Datei gespeichert wird und die Speicherung/Organisation dieser Dateien sehr flexibel ist, verliert eine Werkzeug-Bibliothek für organisatorische Zwecke stark an Bedeutung. Der Benutzer kann seine Werkzeuge in einer beliebigen Verzeichnishierarchie organisieren und sie so benennen, wie es für seine Verwendung und Organisation am besten geeignet ist.

== Werkzeugbit-IDs

Der Werkzeugbit hat keine eigene ID. Die ID ist eine Eigenschaft der Bibliothek. Wenn ein Werkzeugbit zum Erstellen einer Werkzeugsteuerung verwendet wird, wird die ID in der aktuellen Bibliothek zur Standard-Werkzeugnummer im Steuerung. Natürlich kann die Werkzeugnummer in der Werkzeugsteuerung geändert werden.

== Anwendung

== Export

Eine Werkzeugbibliothek kann exportiert werden, um eine http://wiki.linuxcnc.org/cgi-bin/wiki.pl?ToolTable[LinuxCNC-Werkzeugtabelle] (.tbl) zu erstellen.

== JSON-Struktur

[source,python]
----
{
  "tools": [
    {
      "nr": 1,
      "path": "t1.fctb"
    },
    {
      "nr": 2,
      "path": "t2.fctb"
    },
    {
      "nr": 3,
      "path": "t3.fctb"
    }
  ],
  "version": 1
}
----

== Optionen
