= CAM AufbereitungHundeknochen
:page-origin: https://wiki.freecad.org/CAM_DressupDogbone/de
:page-origin-revision: 0d5916218a 2026-06-08
:page-command: CAM_DressupDogbone
:page-icon: CAM_DressupDogbone.svg
:page-menu: CAM → Bahnbearbeitung → Hundeknochen
:page-workbench: CAM
:page-see-also: CAM Haltesteg, CAM Eingangsrampe, CAM Schleppmesser
:page-imported: true

[.fcinfobox]
--
[.fcTitle]
image:CAM_DressupDogbone.svg[CAM AufbereitungHundeknochen,32] *CAM AufbereitungHundeknochen*

Menu location:: menu:CAM[Bahnbearbeitung > Hundeknochen]
Workbenches:: xref:index.adoc[CAM]
Default shortcut:: _None_
Introduced in version:: -
See also:: xref:dressups/tag.adoc[CAM Haltesteg], xref:dressups/ramp-entry.adoc[CAM Eingangsrampe], xref:dressups/drag-knife.adoc[CAM Schleppmesser]
--

== Beschreibung

Der Befehl image:CAM_DressupDogbone.svg[width=24] xref:dressups/dogbone.adoc[CAM AufbereitungHundeknochen] bereitet einen vorhandenen Pfad auf, um Innenecken eines Profils oder einer Konturbearbeitung zu überfräsen. Ein zylindrischer Fräser kann nicht bis in eine spitze Ecke hineinfräsen, ohne mit dem Modell zu kollidieren. In bestimmten Fällen kann es vorteilhaft sein, das Modell zu verletzen und sicherzustellen, dass das Material an der Ecke entfernt wird. Dies ist insbesondere dann erforderlich, wenn sich Teile überschneiden/ineinandergreifen.

== Anwendung

. Ein Kontur- oder Profilpfadobjekt-xref:index.adoc[CAM]-Objekt auswählen.
. Die Option menu:CAM[Bearbeitungspfad > Hundeknochen] aus dem Menü wählen.

== Optionen

* *Seite*: Auf welcher Seite des Pfades die Änderung hinzugefügt wird.
* *Stil*: Art des Überschneidens (Hundeknochen, T-Knochen horizontal, T-Knochen vertikal, T-Knochen lange Kante, T-Knochen kurze Kante).
* *Schnitt*: Der Algorithmus zur Berechnung der Überlänge
* *Benutzerdefiniert*: Wenn Schnitt benutzerdefiniert ist, wird die benutzerdefinierte Eigenschaft zum Festlegen der Länge verwendet.
* [.since]#introduced in 26.3# Bei der adaptiven Schnittart kann auch ein von Null abweichender Wert für *Benutzerdefiniert* verwendet werden, um die maximale Schnittlänge zu begrenzen.

== Einschränkungen

Das Hundeknochen-Aufbereitung benötigt vor und nach der Ecke, an der die Aufbereitung eingefügt werden soll, ein gerades Wegsegment (G1).
