= CAM: Użytkownika
:page-origin: https://wiki.freecad.org/CAM_Custom/pl
:page-command: CAM_Custom
:page-icon: CAM_Custom.svg
:page-menu: CAM → Polecenia dodatkowe → Użytkownika
:page-workbench: CAM
:page-imported: true

[.fcinfobox]
--
[.fcTitle]
image:CAM_Custom.svg[CAM: Użytkownika,32] *CAM: Użytkownika*

Menu location:: menu:CAM[Polecenia dodatkowe > Użytkownika]
Workbenches:: xref:index.adoc[CAM]
Default shortcut:: _None_
Introduced in version:: -
See also:: _None_
--

== Opis

Narzędzie image:CAM_Custom.svg[width=24] xref:operations/custom.adoc[Użytkownika] wstawia obiekt ścieżki, który jest zbudowany z ręcznie utworzonego kodu G-code użytkownika.

Ponieważ polecenie Użytkownika nie zapewnia połączenia z kontrolerem narzędzi, jeśli narzędzie jest używane przez kod G-code użytkownika, jego indeks musi być zapisany razem z kodem M-code uruchomienia wrzeciona aby zostało przekazane do postprocesora. To zapewnia, że zmiany narzędzia i uruchomienie będą prawidłowo wygenerowane.

Przykładowo, aby przekazać do postprocesora, że narzędzie używane w operacji opartej na kodzie G-code użytkownika ma indeks narzędzia 6 i prędkość wrzeciona 10,000, wstaw następujący kod na początku kodu G-code operacji użytkownika:

(T6: 4mm Endmill)

M6 T6

M3 S10000

Zauważ, że prędkości posuwu będą poprawnie generowane przez postprocesor tylko jeśli prędkości posuwu kodu G-code użytkownika są zapisane w jednostkach na sekundę.

== Użycie

. Wciśnij przycisk image:CAM_Custom.svg[width=16] xref:operations/custom.adoc[Użytkownika]
. Wprowadź własny kod G-code we właściwości *G Code* nowo utworzonego obiektu. Zobacz stronę xref:reference/scripting.adoc[Skrypty środowiska CAM] aby sprawdzić wspierane polecenia G-code.

== Właściwości

* *G Code*: Polecenia G-code użytkownika, na których ma być zbudowana ścieżka.
