= CAM Fixture
:page-origin: https://wiki.freecad.org/CAM_Fixture
:page-origin-revision: 8d851eaa90 2025-11-07
:page-menu: CAM → Supplemental Commands → Fixture
:page-imported: true

WARNING: THIS COMMAND IS OBSOLETE<br>
It is not available in [.since]#1.1 and later#.

[.guicommand]
Menu location:: menu:CAM[Supplemental Commands > Fixture]
Workbenches:: xref:index.adoc[CAM]

== Description

The tool image:CAM_Fixture.svg[width=24] xref:job/fixture.adoc[Fixture] sets the Work Offset Coordinate Fixture of the machine CNC controller.

Target Work Offset Coordinates typically include: Fixtures G53 to G59. The G-code is simply the Fixture (G53, G54, etc...). The coordinate offset fixtures represent:

* G53 → Machine coordinate system.
* G54 → Scratchpad coordinate system.
* G55 to G59.9 → Coordinate fixtures allowing work offsets, relative to Homing switches located on the CNC machine, to be used.

The G59 Fixture is used to expand available fixtures. The degree of expansion implemented is CNC machine specific, and this command allows provides for G59.1 to G59.9.

== Usage

. Press the image:CAM_Fixture.svg[width=16] xref:job/fixture.adoc[Fixture] button or use the kbd:[P] then kbd:[F] keyboard shortcut.
. Select the desired Work Offset Fixture from the drop-menu.

== Properties

* *Fixture*: Sets the current fixture point
* *Active*: Defines if this command is active or not when inserted into a compound

== Notes

== Limitations

== Scripting
