= CAM fourth axis
:page-origin: https://wiki.freecad.org/CAM_fourth_axis/pl
:page-imported: true

NOTE: This page is incomplete; it was marked as unfinished on the wiki.

== Opis

Te eksperymentalne narzędzia pozwalają na frezowanie z użyciem czwartej osi https://forum.freecad.org/viewtopic.php?f=15&t=36773[ścian] i https://forum.freecad.org/viewtopic.php?f=15&t=35867[kieszeni]

Te narzędzia są we wczesnym rozwoju. Możliwe są błędy. Dziękujemy za opinie i testowanie.

== Instalacja

Najlepiej zaktualizuj FreeCAD do wersji 0.19.16502 lub wyższej.

Pobierz te skrypty:

* PathProfileFaces.py https://forum.freecad.org/viewtopic.php?f=15&t=36773[dostępny tutaj] i
* PathAreaOp.py https://forum.freecad.org/viewtopic.php?f=15&t=35867[tutaj]
* PathPocketShape.py https://forum.freecad.org/viewtopic.php?f=15&t=35867[tutaj] (do operacji kieszeni)

Umieść je w swojej ścieżce FreeCAD/Mod/CAM/PathScripts, ++*++po++*++ zmianie nazw oryginałów aby je bezpiecznie zachować. Zmień nazwy nowych skryptów na nazwy oryginalnych skryptów. Uruchom FreeCAD ponownie i baw się dobrze.

Używaj na własną odpowiedzialność.

== Ograniczenia

Obecne operacje wspierające czwartą oś nie obsługują złożonych obrotów: tych w osiach X i Y jednocześnie.

Nie ma obecnie integracji GUI ustawień obrotów dla czwartej osi w oficjalnej wersji programu FreeCAD. Wszystkie powiązane ustawienia są w zakładce Dane widoku właściwości dla każdej wspieranej operacji osobno.

== Użycie

=== Profilowanie ścian

* Wybierz ścianę/ściany do operacji jak zazwyczaj
* Kliknij ikonę xref:operations/profile.adoc#profilowanie-ścian[CAM Profilowanie ścian], aby rozpocząć operację
* Zmień ustawienia zgodnie z potrzebami
* Kliknij OK, aby uruchomić operację
* W liście właściwości nowej operacji zmień ustawienie „Enable Rotation” w razie potrzeby dla powierzchni
* Przelicz ponownie operację
* Dostosuj głębokości początkowe/końcowe w razie potrzeby. Głębokość końcowa jest kodowana tak, aby nie przekraczała wybranej powierzchni użytej do profilu.

=== Kieszeń kształtu

* Kliknij ikonę xref:operations/pocket.adoc[CAM Kieszeń kształtu], aby rozpocząć operację.
* Kliknij OK, aby utworzyć operację - bez wybranych powierzchni
* Wybierz nową operację Pocket++_++Shape w oknie zadań
* W liście właściwości operacji przewiń do sekcji CAM i zmień właściwość „Enable Rotation” na żądane ustawienie 4-osiowe.
* Przelicz ponownie operację
* Kliknij dwukrotnie tę samą operację, aby edytować ustawienia w oknie zadań.
* Otwórz zakładkę 'Geometry podstawowa'. Wybierz jedną powierzchnię (preferowaną na razie) i kliknij przycisk 'Dodaj', aby umieścić tę powierzchnię na liście Geometry Bazowej.
* Zmień inne ustawienia operacji zgodnie z potrzebami.
* Kliknij OK, aby zapisać i zastosować zmiany.

== Rozwiązywanie problemów

* Jest właściwość „Inverse Angle”. Może być konieczne jej przełączenie, aby uzyskać poprawne ścieżki dla niektórych powierzchni.
* Ustaw „Enable Rotation” na coś innego niż 'Off', aby profilować powierzchnie prostopadłe, które nie są normalne do osi Z.
* Przełącz właściwość „Reverse Direction”, jeśli ścieżka wydaje się być przesunięta o 180 stopni.
