= CAM: Ulepszenie - rylec
:page-origin: https://wiki.freecad.org/CAM_DressupDragKnife/pl
:page-command: CAM_DressupDragKnife
:page-icon: CAM_DressupDragKnife.svg
:page-menu: CAM → Operacje wykańczające ścieżki → Rylec
:page-workbench: CAM
:page-see-also: CAM: Ulepszenie - znacznik, CAM: Ulepszenie - parkowanie narzędzia, CAM: Ulepszenie - nadcięcie w narożnikach
:page-imported: true

[.fcinfobox]
--
[.fcTitle]
image:CAM_DressupDragKnife.svg[CAM: Ulepszenie - rylec,32] *CAM: Ulepszenie - rylec*

Menu location:: menu:CAM[Operacje wykańczające ścieżki > Rylec]
Workbenches:: xref:index.adoc[CAM]
Default shortcut:: _None_
Introduced in version:: -
See also:: xref:dressups/tag.adoc[CAM: Ulepszenie - znacznik], xref:dressups/ramp-entry.adoc[CAM: Ulepszenie - parkowanie narzędzia], xref:dressups/dogbone.adoc[CAM: Ulepszenie - nadcięcie w narożnikach]
--

== Opis

Narzędzie image:CAM_DressupDragKnife.svg[width=24] xref:dressups/drag-knife.adoc[Rylec] używa krawędzi tnącej zamontowanej na przegubie do cięcia materiałów arkuszowych, takich jak winyl, tektura czy skóra. Punkt tnący nie jest wyrównany z centrum wrzeciona, ale podąża za nim, gdy wrzeciono się porusza. Z powodu tego przesunięcia ścieżka musi zostać zmodyfikowana, aby wydłużyć ją poza punkt końcowy każdego segmentu. Dodatkowo, rylec nie jest zdolny do wykonywania bardzo ciasnych zakrętów. Aby to skompensować, wstawiany jest przegub 'akcja narożna', który chwilowo unosi ostrze i obraca je na nową pozycję.

To narzędzie wykańcza istniejącą ścieżkę aby dodać akcje narożnikowe i przedłużenia krawędzi do cięcia rylcem.

== Użycie

. Wybierz obiekt konturu lub ścieżki profilu.
. Wybierz opcję menu:CAM[Operacje wykańczające ścieżki > Rylec] z menu.

== Opcje

* *Kąt Filtra* : Określa, jak ostry musi być kąt, zanim zostanie wstawiona akcja narożnikowa.
* *Przesunięcie* : Wprowadź, o ile punkt ostrza jest przesunięty względem środka wrzeciona.
* *Wysokość obrotu* : Określa, na jaką wysokość należy podnieść ostrze tnące podczas akcji narożnikowej. Jest to zależne od materiału i powinno być większe dla grubszych materiałów. Idealnie, punkt powinien pozostać lekko w materiale.
