= CAM ToolShape
:page-origin: https://wiki.freecad.org/CAM_ToolShape
:page-origin-revision: 68c5376d73 2025-11-05
:page-imported: true

== Description

ToolShapes are a core part of the xref:tools/index.adoc[CAM Tools] system. ToolShapes are the templates from which ToolBits are created. They represent the specific physical shape of a tool. A ToolShape does not completely describe the bit - for that some additional parameters are needed which will be added when an actual bit is parameterized from the template.

Initially ToolShapes are just FreeCAD documents with a single Body created from the image:Workbench_PartDesign.svg[width=24] https://wiki.freecad.org/PartDesign_Workbench[Part Design ] workbench.

Creating new ToolShapes is an advanced topic. The most commonly needed ToolShapes already exist and are provided with the FreeCAD installation at:

* On Linux it is usually `/usr/lib64/FreeCAD/Mod/CAM/Tools/Shape`
* On Windows it is usually `C:\Program Files\FreeCAD\Mod\CAM\Tools\Shape`
* On macOS it is usually `/Applications/FreeCAD.app/Contents/Resources/Mod/CAM/Tools/Shape`

They are:

::
  `ballend.fcstd`
  +
  `bullnose.fcstd`
  +
  `chamfer.fcstd`
  +
  `drill.fcstd`
  +
  `endmill.fcstd`
  +
  `probe.fcstd`
  +
  `slittingsaw.fcstd`
  +
  `thread-mill.fcstd`
  +
  `v-bit.fcstd`

These can be found in the `Mod/CAM/Tools/Shape/` subdirectory where FreeCAD was installed.

== Usage

. Create a new FreeCAD document.
. Open the image:Workbench_PartDesign.svg[width=16] https://wiki.freecad.org/PartDesign_Workbench[PartDesign Workbench].
. Create a https://wiki.freecad.org/PartDesign_Body[Body] and give the Body a label you want to show up in the bit selection.
. Create a image:PartDesign_NewSketch.svg[width=16] https://wiki.freecad.org/PartDesign_NewSketch[Sketch] on the XZ-plane and draw half the profile of the bit.
. Constrain the bottom most center of the bit on the origin `(0,0)`. This will be the center of the axis on which the G-code will rotate the bit.
* Note: Do not add dimensional constraints at this time.
. Close the Sketch.
. image:PartDesign_Revolution.svg[width=16] https://wiki.freecad.org/PartDesign_Revolution[Revolve] the Sketch around the vertical Sketch axis.
. Open the image:Workbench_CAM.svg[width=16] xref:index.adoc[CAM Workbench].
. Select the Sketch in the https://wiki.freecad.org/Tree_View[Tree View]. This ensures that the PropertyBag created in the next step will be nested in the Body.
. Select the menu:CAM[Utils > PropertyBag] option from the menu.
. A PropertyBag named `Attributes` is created. This PropertyBag will be used to control the dimensions in the Sketch.
. Double-click the PropertyBag in the https://wiki.freecad.org/Tree_View[Tree View].
. The menu:Property Bag[] task panel opens.
. Click the btn:[Add...] button.
. The menu:Create Property[] dialog opens.
. Create a property named `Diameter`. This property is mandatory for ToolBits. Property names are case-sensitive and may not contain spaces.
. Select `Shape` from the menu:Group[] dropdown list.
. Select the appropriate menu:Type[].
. Optionally specify a menu:ToolTip[].
. Click the btn:[OK] button.
. In the menu:Property Bag[] task panel enter a value for the *Diameter* property.
. Similarly add all other required properties.
. Click the btn:[OK] button in the menu:Property Bag[] task panel when done.
. Double-click the Sketch in the https://wiki.freecad.org/Tree_View[Tree View].
. Add dimensional constraints and apply the properties from the created PropertyBag. For example to apply the *Diameter* property:
.. Double-click a dimension.
.. Click the image:Bound-expression.svg[width=16] icon.
.. Enter `<<Attributes>>.Diameter` in the menu:Formula editor[].
.. Click the btn:[OK] button twice.
. Repeat this until the Sketch is fully constrained.
. Save the `FCStd` file where FreeCAD expects to find ToolBit files. See <<description,Description>> above.

* Note 1. If you are denied access to the folder on Windows, start FreeCAD in ADMINISTRATOR mode.
* Note 2. The Body of the ToolBit must be the first object in the https://wiki.freecad.org/Tree_View[Tree View]. These instructions ensure that this is the case.

== Tool Thumbnail Images

ToolBits will have a small icon image of the tool in the https://wiki.freecad.org/Tree_View[Tree View] if the file is saved with thumbnails active.

Important notes:

* Before saving the document make sure you have Save Thumbnail selected, and Add program logo deselected in FreeCAD's preferences.
* Also make sure to switch to Front View and Fit content to screen
* Whatever you see when saving the document will end up being the visual representation of the template
