= CAM Exporter un modèle
:page-origin: https://wiki.freecad.org/CAM_ExportTemplate/fr
:page-origin-revision: 26821945e5 2026-07-08
:page-command: CAM_ExportTemplate
:page-icon: CAM_ExportTemplate.svg
:page-menu: CAM → Exporter comme modèle
:page-workbench: CAM
:page-see-also: CAM Feuille de configuration
:page-imported: true

[.fcinfobox]
--
[.fcTitle]
image:CAM_ExportTemplate.svg[CAM Exporter un modèle,32] *CAM Exporter un modèle*

Menu location:: menu:CAM[Exporter comme modèle]
Workbenches:: xref:index.adoc[CAM]
Default shortcut:: _None_
Introduced in version:: -
See also:: xref:job/setup-sheet.adoc[CAM Feuille de configuration]
--

== Description

L'outil image:CAM_ExportTemplate.svg[width=24] xref:job/export-template.adoc[Exporter un modèle] fournit un mécanisme pratique pour sauvegarder les définitions de tâches couramment utilisées à partir d'une tâche existante. Cela facilite la mise en place de futurs tâches, qui sont en grande partie similaires, en permettant l'importation de modèles de tâches pendant le processus de création de tâches.

menu:Édition[Préférences... > CAM > Préférences des tâches > Valeurs par défaut > Modèle] définit le modèle par défaut.

== Utilisation

. Sélectionnez l'option menu:CAM[Exporter comme modèle] du menu.
. Sélectionnez les éléments à inclure dans la fenêtre de dialogue de configuration menu:Exporter comme modèle[].
. Le modèle doit être enregistré dans le répertoire Macro ou le répertoire CAM, tel que configuré dans les xref:reference/preferences.adoc[CAM Préférences].
. Le nom du modèle doit suivre le modèle `job_<template name>.json`. Lorsqu'il est affiché dans la liste déroulante de la sélection, le préfixe `job_` et l'extension sont omis.
. Appuyez sur le bouton btn:[OK] et enregistrez le modèle.

== Options

== Post-traitement

* Sélection du post-processeur
* Paramètres du post-processeur
* Nom du fichier de sortie

== Brut

* Marge : dimensions du brut
* Position : position du brut

== Feuille de réglage

* Profondeur d'usinage
* Profondeurs de passe
* Vitesses de déplacement de l'outil

== Contrôleurs d'outils

* Contrôleurs d'outils sélectionnés.
