= CAM ToolShape
:page-origin: https://wiki.freecad.org/CAM_ToolShape/pl
:page-imported: true

== Opis

Profile narzędziowe są podstawową częścią systemu xref:tools/index.adoc[narzędzi]. Profile narzędzi są szablonami, na podstawie których tworzone są końcówki narzędzi _(ToolBits)_. Reprezentują one konkretny fizyczny kształt narzędzia. Kształt _(ToolShape)_ nie opisuje w pełni końcówki - do tego potrzebne są dodatkowe parametry, które zostaną dodane, gdy rzeczywista końcówka zostanie określona parametrami na podstawie szablonu.

Początkowo Profile narzędzi są po prostu dokumentami FreeCAD z jednym korpusem utworzonym w środowisku pracy image:Workbench_PartDesign.svg[width=24] https://wiki.freecad.org/PartDesign_Workbench[Projekt Części].

Tworzenie nowych profili narzędzi jest tematem zaawansowanym. Najczęściej potrzebne kształty już istnieją i są dostarczane wraz z instalacją programu FreeCAD:

* W systemie Linux jest to zazwyczaj folder `/usr/lib64/FreeCAD/Mod/CAM/Tools/Shape`.
* Na macOS jest to zazwyczaj folder `/Applications/FreeCAD.app/Contents/Resources/Mod/CAM/Tools/Shape`.
* W systemie Windows jest to zazwyczaj folder `C:\Program Files\FreeCAD\Mod\CAM\Tools\Shape`.

Są to:

::
  `ballend.fcstd`
  +
  `bullnose.fcstd`
  +
  `chamfer.fcstd`
  +
  `drill.fcstd`
  +
  `endmill.fcstd` : `endmill.fcstd`
  +
  `probe.fcstd`
  +
  `slittingsaw.fcstd`
  +
  `thread-mill.fcstd` : `thread-mill.fcstd`
  +
  `v-bit.fcstd`

Można je znaleźć w podkatalogu `/Mod/CAM/Tools/Shape/`, w którym został zainstalowany program FreeCAD.

== Użycie

. Utwórz nowy dokument FreeCAD.
. Otwórz środowisko pracy image:Workbench_PartDesign.svg[width=24] https://wiki.freecad.org/PartDesign_Workbench[Część].
. Utwórz zawartość i nadaj jej nazwę, która będzie wyświetlana przy wyborze końcówki.
. Utwórz szkic w płaszczyźnie XZ i narysuj połowę profilu końcówki narzędzia.
* Umieść górę środka końcówki w punkcie położenia odniesienia `(0,0)`. Będzie to środek osi, na której kod G będzie obracał końcówkę.
* Uwaga: W tym momencie nie należy dodawać żadnych więzów wymiarowych.
. Zamknij szkic.
. Wyciągnij szkic przez image:PartDesign_Revolution.svg[width=16] https://wiki.freecad.org/PartDesign_Revolution[obrót] wokół pionowej osi szkicu.
. Otwórz środowisko pracy image:Workbench_CAM.svg[width=16] xref:index.adoc[CAM].
. Wybierz szkic w oknie https://wiki.freecad.org/Tree_view[widoku drzewa]. Dzięki temu Koszyk właściwości narzędzia skrawającego utworzony w następnym kroku będzie zagnieżdżony w Zawartości.
. Wybierz z menu opcję menu:CAM[Narzędzia > Koszyk własciwości narzędzia skrawającego].
. Zostanie utworzony Koszyk właściwości narzędzia skrawającego o nazwie `Atrybuty`. Ten obiekt będzie używany do kontrolowania wymiarów w szkicu.
. Kliknij dwukrotnie Koszyk właściwości narzędzia skrawającego w oknie https://wiki.freecad.org/Tree_view[widoku drzewa].
. Zostanie otwarty panel zadań menu:Koszyk właściwości[].
. Kliknij przycisk btn:[Dodaj ...].
. Zostanie otwarte okno dialogowe menu:Utwórz właściwość[].
. Utwórz właściwość o nazwie `Diameter`. Ta właściwość jest obowiązkowa dla końcówek narzędzi. W nazwach właściwości rozróżniana jest wielkość liter i nie mogą one zawierać spacji.
. Wybierz `Kształt` z listy rozwijanej menu:Grupa[].
. Wybierz odpowiednie polecenie menu:Typ[].
. Opcjonalnie określ menu:Końcówkę narzędzia[].
. Kliknij przycisk btn:[OK].
. W panelu zadań menu:Koszyk właściwości[] wprowadź wartość dla właściwości *Średnica*.
. W podobny sposób dodaj wszystkie pozostałe wymagane właściwości.
. Po zakończeniu kliknij przycisk btn:[OK] w panelu zadań menu:Koszyk właściwości[].
. Kliknij dwukrotnie szkic w oknie https://wiki.freecad.org/Tree_view[Widoku drzewa].
. Dodaj wiązania wymiarowe i zastosuj właściwości z utworzonego Koszyka właściwości. Na przykład, aby zastosować właściwość *Średnica*:
.. Kliknij dwukrotnie wymiar.
.. Kliknij ikonę image:Bound-expression.svg[width=16].
.. Wpisz wartość `<<Attributes>>.Diameter` w oknie menu:Edytora formuł[].
.. Kliknij dwukrotnie przycisk btn:[OK].
. Powtarzaj tę czynność, aż szkic zostanie w pełni związany.
. Zapisz plik `FCStd` w miejscu, w którym FreeCAD spodziewa się znaleźć pliki Końcówek narzędzi. Zobacz <<opis,opis>> powyżej.

* Uwaga 1. Jeśli w systemie Windows odmówiono Ci dostępu do folderu, uruchom program FreeCAD w trybie ADMINISTRATOR.
* Uwaga 2. Zawartość Zestawu narzędzi musi być pierwszym obiektem w oknie https://wiki.freecad.org/Tree_view[widoku drzewa]. Te instrukcje zapewniają, że tak właśnie jest.

== Miniaturki narzędzi

Końcówki narzędzi będą miały małą ikonę narzędzia w oknie https://wiki.freecad.org/Tree_view[widoku drzewa], jeśli obraz zostanie zapisany z aktywnymi miniaturami.

Ważne uwagi:

* Przed zapisaniem dokumentu upewnij się, że w preferencjach programu FreeCAD zaznaczona jest opcja Zapisz miniaturę, a opcja Dodaj logo programu jest nieaktywna.
* Upewnij się także, że przełączasz się na Widok z przodu i Dopasuj element do ekranu
* Cokolwiek zobaczysz podczas zapisywania dokumentu, będzie to wizualna reprezentacja szablonu.
