= CAM Benutzerdefiniert
:page-origin: https://wiki.freecad.org/CAM_Custom/de
:page-command: CAM_Custom
:page-icon: CAM_Custom.svg
:page-menu: CAM → Zusätzliche Befehle → Benutzerdefiniert
:page-workbench: CAM
:page-imported: true

[.fcinfobox]
--
[.fcTitle]
image:CAM_Custom.svg[CAM Benutzerdefiniert,32] *CAM Benutzerdefiniert*

Menu location:: menu:CAM[Zusätzliche Befehle > Benutzerdefiniert]
Workbenches:: xref:index.adoc[CAM]
Default shortcut:: _None_
Introduced in version:: -
See also:: _None_
--

== Beschreibung

Der Befehl image:CAM_Custom.svg[width=24] xref:operations/custom.adoc[CAM Benutzerdefiniert] fügt ein Pfadobjekt ein, das aus handcodiertem benutzerdefiniertem G-Code erstellt wurde.

Da der benutzerdefinierte G-Code-Befehl keine Verbindung zu einer Werkzeugsteuerung herstellt, muss bei Verwendung eines Werkzeugs durch den benutzerdefinierten G-Code der Werkzeugindex zusammen mit dem M-Code für den Spindelstart geschrieben werden, damit er an den Postprozessor weitergeleitet wird. Dadurch wird sichergestellt, dass Werkzeugwechsel und -starts korrekt generiert werden.

Um beispielsweise dem Postprozessor mitzuteilen, dass das in der benutzerdefinierten G-Code-Operation verwendete Werkzeug den Werkzeugindex 6 und eine Spindeldrehzahl von 10.000 hat, fügt man den folgenden Code am Anfang der benutzerdefinierten G-Code-Operation ein:

(T6: 4mm Endmill)

M6 T6

M3 S10000

Man beachte, dass die Vorschubgeschwindigkeiten vom Postprozessor nur dann korrekt generiert werden, wenn die benutzerdefinierten G-Code-Vorschubgeschwindigkeiten in Einheiten/Sekunde angegeben sind.

== Anwendung

. Die Schaltfläche image:CAM_Custom.svg[width=16] xref:operations/custom.adoc[Benutzerdefiniert] drücken
. Benutzerdefinierten G-Code in die Eigenschaft *G-Code* des neu erstellten Objekts schreiben. Informationen zu den unterstützten G-Code-Befehlen findet man auf der Seite xref:reference/scripting.adoc[CAM Skripten].

== Eigenschaften

* *G Code*: Die benutzerdefinierten G-Code-Befehle zum Erstellen des Pfades.
