= CAM Personnaliser
:page-origin: https://wiki.freecad.org/CAM_Custom/fr
:page-origin-revision: 1e21696259 2026-05-21
:page-command: CAM_Custom
:page-icon: CAM_Custom.svg
:page-menu: CAM → Autres commandes → Personnaliser
:page-workbench: CAM
:page-imported: true

[.fcinfobox]
--
[.fcTitle]
image:CAM_Custom.svg[CAM Personnaliser,32] *CAM Personnaliser*

Menu location:: menu:CAM[Autres commandes > Personnaliser]
Workbenches:: xref:index.adoc[CAM]
Default shortcut:: _None_
Introduced in version:: -
See also:: _None_
--

== Description

La commande image:CAM_Custom.svg[width=24] xref:operations/custom.adoc[Personnaliser] insère un objet _path_ créé à partir de G-code personnalisé codé à la main.

Comme la commande de G-code personnalisé ne fournit aucun lien avec un contrôleur d'outil, si un outil est utilisé par le G-code personnalisé, l'index de l'outil doit être écrit, ainsi que le M-code de démarrage de la broche, afin qu'il soit transmis au post-processeur. Cela garantit que les changements et les démarrages d'outils seront correctement générés.

Par exemple, pour indiquer au post-processeur que l'outil utilisé dans l'opération du G-code personnalisé a l'indice d'outil 6 et une vitesse de broche de 10 000, insérez le code suivant au début de l'opération du G-code personnalisé :

(T6 : 4mm Endmill)

M6 T6

M3 S10000

Notez que les vitesses d'avance ne seront correctement générées par le post-processeur que si les vitesses d'avance du G-code personnalisé sont écrites en unités/seconde.

== Utilisation

. Pressez le bouton image:CAM_Custom.svg[width=16] xref:operations/custom.adoc[Personnaliser]
. Écrivez le G-code adapté dans la propriété *G Code* de l'objet juste créé. Voir la page xref:reference/scripting.adoc[CAM Script] pour les commandes G-code acceptées.

== Propriétés

* *G Code* : commandes G-code personnalisées pour programmer le parcours.
