= CAM Parcours hélicoïdal
:page-origin: https://wiki.freecad.org/CAM_Helix/fr
:page-origin-revision: eb09934cef 2026-07-08
:page-command: CAM_Helix
:page-icon: CAM_Helix.svg
:page-menu: CAM → Détourer hélicoïdalement
:page-workbench: CAM
:page-imported: true

NOTE: This page is incomplete; it was marked as unfinished on the wiki.

[.fcinfobox]
--
[.fcTitle]
image:CAM_Helix.svg[CAM Parcours hélicoïdal,32] *CAM Parcours hélicoïdal*

Menu location:: menu:CAM[Détourer hélicoïdalement]
Workbenches:: xref:index.adoc[CAM]
Default shortcut:: _None_
Introduced in version:: -
See also:: _None_
--

== Description

La commande image:CAM_Helix.svg[width=24] xref:operations/helix.adoc[Parcours hélicoïdal] ajoute une opération de détourage hélicoïdale à la tâche. Le parcours hélicoïdal dans le sens horaire produit des commandes G-code (G2). Le sens anti-horaire produit des commandes de G-code (G3). Le pourcentage de recouvrement spécifie le recouvrement concentrique en pourcentage du diamètre de l'outil. Une ou plusieurs parcours hélicoïdales seront créés à des diamètres progressivement différents, pour détourer le trou.

== Utilisation

* Sélectionnez l'image:Workbench_CAM.svg[width=16] xref:index.adoc[atelier CAM].
* Sélectionnez l'icône image:CAM_Helix.svg[width=24] ou kbd:[CAM] → image:CAM_Helix.svg[width=24] Détourer hélicoïdalement du menu supérieur. Cela ouvre le image:CAM_Helix.svg[width=24] panneau de configuration du parcours hélicoïdal.
* Une pop-up *Choisir un contrôleur d'outils* vous invite à sélectionner un contrôleur d'outils. Dans les anciennes versions, dans l'onglet image:CAM_Helix.svg[width=24] Opération, choisissez un contrôleur d'outil et confirmez en appuyant sur btn:[Appliquer].
* Ouvrez l'onglet Géométrie de base. Tous les trous disponibles compatibles avec l'outil Parcours hélicoïdal dans le modèle de tâche pourront être sélectionnés pour le traitement. Dans la https://wiki.freecad.org/3D_View[vue 3D], sélectionnez les trous par leur arête ou les faces de leur paroi et ajoutez-les avec le bouton btn:[Ajouter]. Vérifiez qu'ils apparaissent dans la liste. Confirmez que la liste correspond aux trous destinés à être traités.
* Pour supprimer des trous, sélectionnez-les dans la liste et appuyez sur le bouton btn:[Supprimer].
* Assurez-vous que la profondeur initiale, la profondeur finale et le pas de descente (le pas de l'hélicoïde) sont corrects. Ajustez-les si ce n'est pas le cas.
* Assurez-vous que les hauteurs de sécurité et de dégagement sont correctes.
* Dans l'onglet Opération, spécifiez la surface de départ de l'hélicoïde (extérieure/intérieure), la direction (sens horaire/sens anti-horaire) et le pourcentage de recouvrement.
* Cliquez sur btn:[Appliquer] pour créer ou mettre à jour le parcours, btn:[OK] pour appliquer et fermer le panneau, ou btn:[Annuler] pour abandonner et fermer le panneau.

== Options

*Décalage supplémentaire* ajoute une marge de matériau à ne pas usiner. Il s'agit généralement d'une opération séparée pour permettre une légère finition.

*Pas maximal* remplace _Pas_ de l'hélicoïde et limite le pas maximal de l'hélicoïde lorsqu'il est différent de zéro. [.since]#introduced in 26.3#

*Angle maximum de la rampe* de l'hélicoïde limite l'angle d'entrée de la rampe lorsqu'il est différent de zéro. Le pas est calculé pour chaque rayon de l'hélicoïde.

*Rayon de départ* n'est pas disponible dans le panneau de tâches _Détourer hélicoïdalement_ mais peut être édité directement dans l'https://wiki.freecad.org/Property_View[éditeur de propriétés]

Il s'agit du rayon de matière restant au centre. Par défaut, il est égal à zéro, ce qui donne un parcours où l'outil touche juste l'axe du trou. Cela produit un parcours central découpant un trou deux fois plus grand que le diamètre de l'outil.

Si ce paramètre est réglé sur une valeur négative, il peut permettre un rayon du parcour hélicoïdal plus petit. Par exemple, un rayon négatif égal au rayon de l'outil produira un parcour hélicoïdal de rayon zéro, c'est-à-dire une coupe en plongée avec la fraise en bout, si l'outil est approprié. Cela fonctionnera comme première coupe dans une opération en plusieurs passes, mais toute tentative de créer un parcour hélicoïdal avec un outil de la même taille que le trou dans le modèle sera rejetée.

== Commentaires

* La limite du pas de l'hélicoïde n'est pas exactement respectée. Elle est toujours arrondie pour donner un nombre complet de tours de la profondeur de départ à la profondeur finale.
* De même, le pas d'avance n'est pas exactement respecté. Il est toujours arrondi pour donner un nombre de pas égaux.

Le paramètre d'avance est constant pour toutes les coupes et est basé sur la position de l'axe de l'outil. L'avance réelle de l'arête de coupe de l'outil peut donc varier considérablement entre la coupe la plus intérieure et la surface extérieure. Si les dimensions de la tâche produisent un diamètre de parcours plus petit que le diamètre de l'outil, cela peut conduire à des vitesses de coupe beaucoup plus rapides que l'avance donnée pour l'outil dans le contrôleur d'outil. Il peut être nécessaire d'en tenir compte lors de la sélection de "l'avance et des vitesses" dans le xref:tools/tool-controller.adoc[contrôleur d'outil] pour la tâche.

De plus, la mise en œuvre actuelle n'utilise que la vitesse horizontale de l'outil pour les parcours hélicoïdales, même dans le cas où une spirale serrée peut être proche d'une coupe verticale.

== Propriétés

=== Données

Vide

=== Vue

Vide

== Script

_Voir aussi :_ https://wiki.freecad.org/FreeCAD_Scripting_Basics[FreeCAD Script de base].

Exemple :

[source,python]
----
#Place code example here.
----
