= OpenCamLib
:page-origin: https://wiki.freecad.org/OpenCamLib
:page-origin-revision: 634d2069b4 2025-07-05
:page-imported: true

== Description

OpenCamLib (OCL) is an open source library aiming to provide computer aided manufacturing (CAM) algorithms. FreeCAD uses OCL in the experimental image:Path_Surface.svg[width=24] xref:operations/surface.adoc[3D Surface] path operations and other experimental features.

Github: https://github.com/aewallin/opencamlib

Website: http://www.anderswallin.net/CAM/

== Installing

=== Windows

*Note:* Beginning with FreeCAD version 0.19, OCL should be included with all Windows distribution packages.

To install OCL on Windows, follow these instructions.

. Obtain the Python version of OpenCamLib (OCL).
* Build from https://github.com/aewallin/opencamlib[source] using the Python version used by your FreeCAD version. Peter Lama's https://github.com/peterlama/opencamlib[fork of the same] source has project files for a MSVC build.
* Download the Python 2.7 x86/x64 https://github.com/sgrogan/opencamlib/releases[binary] by sgrogan on GitHub.
* Download the Python 3.6 x64 https://github.com/sgrogan/opencamlib/releases[binary] by sgrogan on GitHub.
. Navigate to your OCL build _or_ binary folder
. Copy the *ocl.pyd* library file
. Proceed with one of the following four(4) options:
* Navigate to your *FreeCAD++\++lib* folder, and paste the *ocl.pyd* file there. (''This is the preferred option.'')
* Navigate to your *FreeCAD++\++bin* folder, and paste the *ocl.pyd* file there.
* Navigate to your *FreeCAD++\++Mod* folder. Create a new folder, *OCL*. Enter the *OCL* folder and paste the *ocl.pyd* file.
* Navigate to your *%USERPROFILE%++\++AppData++\++Roaming++\++FreeCAD* folder. Create a new folder, *Mod*. Enter the *Mod* folder. Create a new *OCL* folder. Enter the *OCL* folder and paste the *ocl.pyd* file. (''This is the least preferred option.'')
. Restart FreeCAD
. Verify proper installation
.. Click *View* → *Panels* → *Python console*.
.. Type "*import ocl*" into the Python console and press the *enter* key.
.. If no error appears, you have correctly installed OCL
* If you receive an error:
** Check the placement and name of the *ocl.pyd* file as instructed above
** Verify the correct architecture type of the OCL library you installed - x86 or x64
** Verify the Python version used to build the OCL library is the same as that of your FreeCAD software - 2.7 or 3.6 currently

=== Linux

The repository is https://github.com/aewallin/opencamlib[here] and contains basic installation instructions.

Before beginning installation, or during the installation process, you will probably find you need to install some additional packages:

==== Ubuntu/Debian

For example:

[source,bash]
----
sudo apt install cmake
sudo apt install libboost-program-options-dev
# Optional, for documentation:
sudo apt-get install doxygen
sudo apt-get install texlive-full
----

Note: the "libboost-program-options-dev" may be substituted with "libboost-all-dev".

If you are struggling, carefully review any error messages you get during the cmake and make phases as you may need to install additional packages.

==== Archlinux

. Install OpenCamLib from the https://aur.archlinux.org/packages/opencamlib-git[AUR package].
. Then run the following code snippet inside FreeCAD's https://wiki.freecad.org/Python_console[Python console]

[source,bash]
----
import sys
sys.path.append('/usr/opencamlib/')
import ocl
----

==== Python 3

Identify the version of cmake you have installed with `cmake --version`

For cmake ++>++= 3.12, add these flags:

[source,bash]
----
cmake -DBUILD_PY_LIB=ON -DUSE_PY_3=ON -DCMAKE_BUILD_TYPE=Release ../src -Wno-dev
----

For cmake ++<++ 3.12 (like in Ubuntu 18.04, which has 3.10), first you'll need to edit `src/pythonlib/pythonlib.cmake`, and apply this patch:

`Index: opencamlib-2019.07/src/pythonlib/pythonlib.cmake` +
`===================================================================` +
`--- opencamlib-2019.07.orig/src/pythonlib/pythonlib.cmake` +
`{plus}{plus}{plus} opencamlib-2019.07/src/pythonlib/pythonlib.cmake` +
`@@ -48,13 {plus}48,13 @@ if($++{++CMAKE++_++VERSION} VERSION++_++LESS "3.12.0` +
`     message("Python not found")` +
`   endif()` +
`   execute++_++process(` +
`-    COMMAND $++{++PYTHON++_++EXECUTABLE} -c "from distutils.sysconfig import get++_++python++_++lib; print get++_++python++_++lib(0,0,++\++"/usr/local++\++")"` +
`{plus}    COMMAND $++{++PYTHON++_++EXECUTABLE} -c "import site; print(site.getsitepackages()++[++-1++]++)"` +
`     OUTPUT++_++VARIABLE PYTHON++_++SITE++_++PACKAGES` +
`     OUTPUT++_++STRIP++_++TRAILING++_++WHITESPACE` +
`   ) ++#++ on Ubuntu 11.10 this outputs: /usr/local/lib/python2.7/dist-packages` +
` ` +
`   execute++_++process(` +
`-    COMMAND $++{++PYTHON++_++EXECUTABLE} -c "from distutils.sysconfig import get++_++python++_++lib; print get++_++python++_++lib(plat++_++specific=1,standard++_++lib=0,prefix=++\++"/usr/local++\++")"` +
`{plus}    COMMAND $++{++PYTHON++_++EXECUTABLE} -c "import site; print(site.getsitepackages()++[++-1++]++)"` +
`     OUTPUT++_++VARIABLE PYTHON++_++ARCH++_++PACKAGES` +
`     OUTPUT++_++STRIP++_++TRAILING++_++WHITESPACE` +
`   )`

Then, in order for Python 3 to be detected correctly you'll need to add 2 more flags to the cmake line:

[source,bash]
----
cmake -DBUILD_PY_LIB=ON -DUSE_PY_3=ON -DPYTHON_EXECUTABLE="$(which python3)" -DPYTHON_VERSION_SUFFIX=3 -DCMAKE_BUILD_TYPE=Release ../src -Wno-dev
----

See the FreeCAD forum at https://forum.freecad.org/viewtopic.php?p=316970#p316988[Re: How to activate openCamLib after compiling it], and a few posts following.

=== Mac

[source,bash]
----
git clone https://github.com/aewallin/opencamlib
cd opencamlib
mkdir build
cd build
cmake -DBUILD_PY_LIB=ON -DUSE_PY_3=ON -DCMAKE_BUILD_TYPE=Release .. -Wno-dev
make -j4
make install
----

To test the build enter the following in the https://wiki.freecad.org/Python_console[Python console]:

[source,python]
----
import area
import ocl
dir(ocl)
----

The return value should be:

[source,python]
----
['AdaptivePathDropCutter', 'AdaptivePathDropCutter_base', 'AdaptiveWaterline', 'AdaptiveWaterline_base', 'Arc', 'ArcSpanType', 'BallConeCutter', 'BallCutter', 'BatchDropCutter', 'BatchDropCutter_base', 'BatchPushCutter', 'BatchPushCutter_base', 'Bbox', 'BullConeCutter', 'BullCutter', 'CCPoint', 'CCType', 'CLPoint', 'CompBallCutter', 'CompCylCutter', 'ConeConeCutter', 'ConeCutter', 'CutterLocationSurface', 'CylConeCutter', 'CylCutter', 'Ellipse', 'EllipsePosition', 'Fiber', 'Fiber_base', 'Interval', 'Line', 'LineCLFilter', 'LineCLFilter_base', 'LineSpanType', 'MillingCutter', 'Path', 'PathDropCutter', 'PathDropCutter_base', 'Path_base', 'Point', 'STLReader', 'STLSurf', 'STLSurf_base', 'SpanType', 'Triangle', 'Triangle_base', 'Waterline', 'Waterline_base', 'WeaveVertexType', 'ZigZag', 'ZigZag_base', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'eps', 'epsD', 'epsF', 'version']
----

In case of an error the return value will be:

[source,python]
----
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
----

For cmake the Release option is very important, when using Debug area and ocl will collide and either library will not load (depending on what what was loaded first).

== More help

In case you run into difficulties, you may find additional help at these forum posts:

* https://forum.freecad.org/viewtopic.php?t=19205[Windows]
* https://forum.freecad.org/viewtopic.php?t=18017[Linux]

== Acknowledgments

Thank you to http://www.anderswallin.net/about/[Dr. Anders Wallin] for providing OCL to the public.
