= CAM Post-traitement
:page-origin: https://wiki.freecad.org/CAM_Post/fr
:page-origin-revision: 3b58faaa1d 2026-07-08
:page-command: CAM_Post
:page-icon: CAM_Post.svg
:page-menu: CAM → Post-traiter
:page-workbench: CAM
:page-shortcut: P P
:page-imported: true

[.fcinfobox]
--
[.fcTitle]
image:CAM_Post.svg[CAM Post-traitement,32] *CAM Post-traitement*

Menu location:: menu:CAM[Post-traiter]
Workbenches:: xref:index.adoc[CAM]
Default shortcut:: kbd:[kbd:[P] kbd:[P]]
Introduced in version:: -
See also:: _None_
--

== Description

La commande image:CAM_Post.svg[width=24] xref:output/post-process.adoc[Post-traitement] exporte la image:CAM_Job.svg[width=16] xref:job/job.adoc[CAM Tâche] sélectionnée vers un fichier G-code.

*Chaque contrôleur CNC parle un dialecte G-code spécifique, nécessitant un post-processeur à correction dialectale pour traduire la sortie finale à partir du dialecte G-code interne agnostique de FreeCAD*.

=== Fonctions typiques du post-processeur

* L'utilisation d'une extension de fichier G-code correcte pour la sortie de la tâche.
* Sélection des commandes G-code. Les commandes numériques prennent généralement en charge un sous-ensemble de commandes G-code disponibles. Le super-ensemble de commandes G-code contient des commandes puissantes et spécialisées qui doivent être traitées à l'aide de plusieurs commandes plus simples. Les post-processeurs sont écrits pour sélectionner le meilleur G-code pour une opération, disponible sur la cible.
* Formatage de la syntaxe du G-code en réordonnant les entrées Feed (avance), X, Y, Z, A et B ainsi que la précision.
* Insertion d'un préambule pour définir les unités, le format des unités, le plan de travail, le système de coordonnées, etc...
* Insertion d'un post-amble pour stationner la machine, l'arrêter, traiter les arguments.
* Insérer des changements d'outils, ou les supprimer entre les opérations suivantes utilisant le même outil.
* Formatage des informations relatives à l'avance et à la vitesse en tours par minute ou par seconde.
* Formatage de l'appellation et de l'appel des fonctions.

=== Personnalisation du post-processeur

Si vous souhaitez écrire votre propre post-processeur, consultez la page xref:output/postprocessor-customization.adoc[CAM Personnaliser le post-processeur].

*Remarque :* plusieurs post-processeurs fournis génèrent un code adapté à de nombreux contrôleurs CNC ou peuvent être utilisés comme modèles pour des modifications.

Les post-processeurs contiennent des indicateurs de configuration et sont conçus pour être ajustés en ajoutant des G-codes et M-codes aux définitions fournies pour :

* Initialisation de la machine
* Finalisation de la tâche
* Changements d'outils
* Refroidissement activé/désactivé
* Etc...

Les post-processeurs utilisent le xref:reference/scripting.adoc#le-format-g-code-interne-de-freecad[G-code interne de FreeCAD] en conjonction avec les définitions de configuration du post-processeur, afin de générer un G-code correct du point de vue dialectal pour les machines cibles. Cela permet à l'atelier CAM de générer du G-code correct pour cibler différents contrôleurs de machines CNC en appelant différents post-processeurs.

Les types de contrôleur de machine CNC comprennent :

* Fraiseuses CNC
* Tours CNC
* Imprimantes 3D
* Couteaux tractés
* Découpeurs laser
* Graveurs
* Découpeurs à torche plasma
* Cintreuses
* Usinage par décharge électrique
* Etc.

Si une seule machine CNC est utilisée ou si toutes les machines CNC partagent un post-processeur commun, l'atelier CAM ne doit inclure qu'un seul post-processeur. Si un seul post-processeur est insuffisant pour générer un G-code pour tous les contrôleurs CNC cibles, plusieurs post-processeurs doivent être installés.

== Utilisation

. Sélectionnez une image:CAM_Job.svg[width=16] xref:job/job.adoc[tâche] dans l'https://wiki.freecad.org/Tree_View[arborescence].
. Il existe plusieurs façons de lancer la commande :
* Appuyez sur le bouton image:CAM_Post.svg[width=16] xref:output/post-process.adoc[Post-traiter].
* Sélectionnez l'option menu:CAM[Post-traiter] du menu.
* Utilisez le raccourci clavier : kbd:[P] puis kbd:[P].
. Confirmez le nom et le répertoire de menu:Fichier de sortie[].

== Options

Les propriétés du fichier de sortie et du post-processeur peuvent être définies dans la xref:job/job.adoc[tâche] à tout moment, avant de lancer le post-processeur.

Les post-processeurs fournis sont écrits avec des commentaires indiquant les zones contenant des balises, des variables de configuration et des sections de G-codes et de M-codes qui doivent être utilisés par le post-processeur pour configurer la sortie.

Les indicateurs True/False de la configuration type incluent :

* *OUTPUT++_++COMMENTS* (True=Autoriser, False=Supprimer) : utilisé pour insérer des commentaires texte dans le fichier G-code de sortie.
* *OUTPUT++_++HEADER* (True=Autoriser, False=Supprimer) : utilisé pour insérer des en-têtes de texte dans le fichier G-code de sortie.
* *OUTPUT++_++LINE++_++NUMBERS* (True=Autoriser, False=Supprimer) : utilisé pour insérer des numéros de ligne dans le fichier G-code de sortie.
* *SHOW++_++EDITOR* (True=Autoriser, False=Supprimer) : utilisé pour afficher le G-code de sortie dans une fenêtre contextuelle lors de l'appel du Post-processeur.
* *MODAL* (True=Autoriser, False=Supprimer) : utilisé pour réduire le nombre de lignes G-code en sortie en supprimant les informations dU Mode lorsque le Mode ne change pas.

Les variables de configuration typiques incluent:

* *LINENR* (numéro de ligne) : utilisé pour définir l'index du numéro de ligne.
* *UNITS* (G20 ou G21) : utilisé pour communiquer explicitement au contrôleur CNC cible quelles unités utiliser pour interpréter le fichier de sortie final.
* *MACHINE++_++NAME* (nom de la fraiseuse CNC cible) : utilisé pour insérer une étiquette de nom de machine dans le fichier de sortie final.
* *PRECISION* : utilisé pour définir le nombre de chiffres à inclure après la décimale dans le fichier de sortie final

Les sections de configuration typiques incluent :

* *PREAMBULE* : configuration du code insérée au début de la tâche.
* *POSTAMBLE* : configuration du code annexée à la tâche, permettant de stationner la machine, etc.
* *TOOL++_++CHANGE* : code inséré avec chaque changement d'outil dans la tâche.

menu:Édition[Préférences > CAM > Préférences des tâches > Onglet ''Post-processeur'' > Post-processeur] permet de définir le post-processeur par défaut sélectionné lors de la création de la tâche. Ceci permet à l'atelier CAM d'être configuré pour n'afficher que les post-processeurs souhaités et de définir une valeur par défaut.

Les paramètres de post-traitement peuvent provenir soit du post-processeur sélectionné pour la tâche, soit d'une configuration de machine choisie. Si l'on utilise une configuration de machine, celle-ci peut définir le post-processeur et les options de sortie associées.

Les post-processeurs inclus sont enregistrés dans *FreeCAD/Mod/CAM/CAM/Post/scripts* par défaut :

* centroid
* comparams
* dxf
* dynapath
* grbl, y compris la prise en charge des blocs d'en-tête bCNC à l'aide de l'argument de sortie du travail --bcnc
* jtech (laser)
* http://linuxcnc.org/docs/html/gcode/g-code.html#gcode:g17-g19.1[linuxcnc]
* mach3++_++mach4
* nccad
* opensbp
* phillips
* refactorisé++*++ (Ces post-processeurs sont en cours d'élaboration et vont beaucoup évoluer)
* rml
* smoothie
* uccnc

== Limitations

* *N'utilisez pas* le menu menu:Fichier[Exporter] pour exporter vers le G-code, cela produirait un G-code endommagé !
